services:
  hits:
    container_name: hits
    image: lexunok/hits:latest
    environment:
      TZ: Europe/Yekaterinburg
      SERVICE_USERNAME: lexunok
      SERVICE_PASSWORD: 0uLu91hYOE28yMe0S5nB
      JWT_SECRET: eKVnyhB2Hjyh2Il2hI4HC2oyaHIWn1tuvU4kXXafLGiGy6qBkwBHOmLwSsbAt5jn
      MAIL_LOGIN: VSHTST.hits0@gmail.com
      MAIL_PASSWORD: cxwxdgrkjzllyaln
    depends_on:
      - postgres
    volumes:
      - spring:/data/spring
    ports:
      - '80:80'
    networks:
      - spring
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      TZ: Europe/Yekaterinburg
      POSTGRES_PASSWORD: 0uLu91hYOE28yMe0S5nB
      POSTGRES_USER: lexunok
      POSTGRES_DB: hits
    networks:
      - spring
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
networks:
  spring:
    driver: bridge
volumes:
  postgres:
  spring:
