import { User, UserTelegram } from '@Domain/User'
import { Profile } from '@Domain/Profile'
import UsersGroup from '@Domain/UsersGroup'
import Company from '@Domain/Company'
import UsersSkills from '@Domain/UsersSkills'
import { Skill } from '@Domain/Skill'
import { Idea, IdeaSkills, Rating } from '@Domain/Idea'
import Comment from '@Domain/Comment'
import {
  RequestToTeam,
  Team,
  TeamExperience,
  TeamInvitation,
  TeamMember,
  TeamSkills,
} from '@Domain/Team'
import Notification from '@Domain/Notification'
import { IdeaMarket, IdeaMarketAdvertisement } from '@Domain/IdeaMarket'
import { Market } from '@Domain/Market'
import { RequestTeamToIdea } from '@Domain/RequestTeamToIdea'
import {
  TaskMovementLog,
  Project,
  ProjectMember,
  Sprint,
  SprintMarks,
  Task,
} from '@Domain/Project'
import { Tag } from '@Domain/Tag'
import { InvitationTeamToIdea } from '@Domain/InvitationTeamToIdea'
import { AverageMark } from '@Domain/ReportProjectMembers'

export const usersMocks: User[] = [
  {
    id: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    token: '10296538',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    roles: [
      'INITIATOR',
      'PROJECT_OFFICE',
      'EXPERT',
      'ADMIN',
      'MEMBER',
      'TEAM_LEADER',
    ],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '1111111111',
    studyGroup: 'AAAA-22-1',
  },
  {
    id: '1',
    token: '1',
    email: '1@mail.com',
    firstName: 'Иван',
    lastName: 'Иванович',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '22222222222',
    studyGroup: 'BBBB-22-1',
  },
  {
    id: '2',
    token: '059182',
    email: '2@mail.com',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '33333333333',
    studyGroup: 'CCCC-22-1',
  },
  {
    id: '3',
    token: '163097',
    email: '3@mail.com',
    firstName: 'Владелец',
    lastName: 'Владелец',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '44444444444',
    studyGroup: 'DDDD-22-1',
  },
  {
    id: '4',
    token: '8755764',
    email: '4@mail.com',
    firstName: 'Винрит',
    lastName: 'Загрев',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '55555555555',
    studyGroup: 'EEEE-22-1',
  },
  {
    id: '5',
    token: '836444',
    email: '5@mail.com',
    firstName: 'Версаль',
    lastName: 'Кустерман',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '66666666666',
    studyGroup: 'FFFF-22-1',
  },
]

export const usersTelegramMocks: UserTelegram[] = [
  {
    userId: usersMocks[0].id,
    userTag: 'baobao',
    chatId: '0',
    isVisible: true,
  },
  {
    userId: usersMocks[1].id,
    userTag: '@chipichipi',
    chatId: '5',
    isVisible: false,
  },
  {
    userId: usersMocks[1].id,
    userTag: '@chapachapa',
    chatId: null,
    isVisible: true,
  },
]

export const tagsMocks: Tag[] = [
  {
    id: '0',
    name: 'Фронтенд',
    color: '#0D6EFD',
    confirmed: true,
  },
  {
    id: '1',
    name: 'Бекенд',
    color: '#FFA800',
    confirmed: true,
  },
  {
    id: '2',
    name: 'Рефактор',
    color: '#AEA709',
    confirmed: true,
  },
  {
    id: '3',
    name: 'Изучения',
    color: '#13C63A',
    confirmed: true,
  },
  {
    id: '4',
    name: 'Бегать',
    color: '#BB2D3B',
    confirmed: false,
  },
  {
    id: '5',
    name: 'UI/UX',
    color: '#6fa8dc',
    confirmed: true,
  },
  {
    id: '6',
    name: 'Уведомления',
    color: '#6aa84f',
    confirmed: true,
  },
  {
    id: '7',
    name: 'Интеграция',
    color: '#674ea7',
    confirmed: true,
  },
  {
    id: '8',
    name: 'Оптимизация',
    color: '#cc0000',
    confirmed: true,
  },
  {
    id: '9',
    name: 'Статистика',
    color: '#76a5af',
    confirmed: true,
  },
  {
    id: '10',
    name: 'Безопасность',
    color: '#660000',
    confirmed: true,
  },
  {
    id: '11',
    name: 'Дизайн',
    color: '#8fce00',
    confirmed: true,
  },
]

export const skillsMocks: Skill[] = [
  {
    id: '0',
    name: 'JavaScript',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '1',
    name: 'Python',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '2',
    name: 'Rust',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '3',
    name: 'Swift',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '4',
    name: 'Kotlin',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '5',
    name: 'Go',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '6',
    name: 'React JS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '7',
    name: 'C++',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '8',
    name: 'VueJS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '9',
    name: 'Angular',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '10',
    name: 'NodeJS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '11',
    name: 'Docker',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '12',
    name: 'Git',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '13',
    name: 'Grafana',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '14',
    name: 'Elasticsearch',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '15',
    name: 'MongoDB',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '16',
    name: 'PostgreSQL',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '17',
    name: 'MySQL',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '18',
    name: 'SQLite',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '19',
    name: 'Redis',
    type: 'DATABASE',
    confirmed: true,
  },
]

export const teamMembersMocks: TeamMember[] = [
  {
    id: '277922d4-e08a-430b-9b94-949dc32681b4',
    teamId: '1',
    userId: '1',
    email: 'timyr@mail.com',
    firstName: 'Тимур',
    lastName: 'Минязев',
    skills: [],
  },
  {
    id: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    teamId: '1',
    userId: '0',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    skills: [],
  },
  {
    id: '2',
    teamId: '0',
    userId: '3',
    email: 'admin@mail.com',
    firstName: 'Админ',
    lastName: 'Иванов',
    skills: [],
  },
  {
    id: '3',
    teamId: '1',
    userId: '4',
    email: 'deins@mail.com',
    firstName: 'Денис',
    lastName: 'Денисович',
    skills: [],
  },
]

export const teamsMocks: Team[] = [
  {
    id: '01',
    name: 'Визитка',
    closed: true,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 4,
    owner: teamMembersMocks[1],
    leader: teamMembersMocks[1],
    members: [
      teamMembersMocks[0],
      teamMembersMocks[1],
      teamMembersMocks[2],
      teamMembersMocks[3],
    ],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
    hasActiveProject: true,
  },
  {
    id: '1',
    name: 'Кактус',
    closed: false,
    hasActiveProject: false,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 4,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [teamMembersMocks[0], teamMembersMocks[2], teamMembersMocks[3]],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
  },
  {
    id: '2',
    name: 'Карасики',
    closed: false,
    hasActiveProject: false,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 4,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [teamMembersMocks[0], teamMembersMocks[2], teamMembersMocks[3]],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
  },
]

export const ideasMarketMocks: IdeaMarket[] = [
  {
    id: 'dfaedabe-2b3b-44e7-851e-35c9c6409869',
    ideaId: 'dfaedabe-2b3b-44e7-851e-35c9c6409869',
    initiator: usersMocks[0],
    team: null,
    marketId: '201',
    name: 'Цифровой помощник сотрудника приемной комиссии университета',
    problem: 'null',
    description: 'null',
    solution:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта ',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 7,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '74d9f126-e188-4d1e-abb3-d494e5e5fa89',
        name: 'Keras',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '2a03579d-9e40-4e85-a60e-6605a5a961dd',
        name: 'Scikit Learn',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: '279b3fbf-de63-426f-bf9f-0c01ea19706b',
    ideaId: '279b3fbf-de63-426f-bf9f-0c01ea19706b',
    initiator: {
      id: '2bafebe0-9514-43e0-badf-548388dfa2d4',
      email: 'warkingzar@gmail.com',
      lastName: 'Зайко',
      firstName: 'Антон',
    } as User,
    team: null,
    marketId: '201',
    name: 'PW Technology: Интерактивное виртуальное образование с 3D тренажерами',
    problem: 'null',
    description: 'null',
    solution:
      'Разработка проекта по обучению людей взаимодействию с оборудованием в игровой форме, где каждый пользователь сможет примерить на себя роль нефтяника, электрика, строителя и других профессий, требующих специальных навыков и знаний.\n',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 8,
    stack: [
      {
        id: '31ea96a6-4da7-4618-a9f7-0f2531c35033',
        name: 'Unreal Engine GameMode',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: '15bc47fb-e894-4698-b86f-52be31fd7064',
        name: 'C++',
        type: 'LANGUAGE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'c2d8b869-2731-4c37-b0de-17c1950a770f',
    ideaId: 'c2d8b869-2731-4c37-b0de-17c1950a770f',
    initiator: {
      id: '09e6884f-65c5-4cd5-98f1-2f4ebb5823c0',
      email: 'l.a.nikiforova@tmn3.etagi.com',
      lastName: 'Никифорова',
      firstName: 'Любовь',
    } as User,
    team: null,
    marketId: '201',
    name: 'EMetrics.Viewer',
    problem: 'null',
    description: 'null',
    solution:
      'WEB-приложение (конкретная реализация выбирается разработчиками в рамках стэка React|Vue, NodeJS|Python)\nИспользование существующих у заказчика оперативных и аналитических БД в том числе тестовых.\nИспользование VPN (предоставляется заказчиком) для подключения к ресурсам заказчика с машин разработчиков.',
    result: 'null',
    maxTeamSize: 5,
    customer: 'null',
    position: 9,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'd908579e-4528-4268-bb7f-e072c5dc3f4d',
        name: 'GOLANG',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '8e22a7d8-4148-4c73-80dc-8834c51fe800',
        name: 'C#',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '743145bc-c8ac-460b-a908-fdf3269d52d9',
        name: 'Vue',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'ca34b1a6-c56e-40b4-b77d-454eb971b059',
        name: 'Redis',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'a51c17fd-c089-448c-be7b-714bceee8109',
    ideaId: 'a51c17fd-c089-448c-be7b-714bceee8109',
    initiator: {
      id: '12c1534d-c6d1-4515-b531-ea380d75b772',
      email: 'd.shirokov@unlim.group',
      lastName: 'Широков',
      firstName: 'Дмитрий',
    } as User,
    team: null,
    marketId: '2',
    name: 'Расчет строительных материалов. ',
    problem: 'null',
    description: 'null',
    solution:
      'Система, которая позволяет указать размерные характеристики объекта строительства и\\или работ, выбрать требуемый материал и получить расчет количества этих материалов.\nПродумать систему придется в рамках реализации проекта.',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 10,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'd908579e-4528-4268-bb7f-e072c5dc3f4d',
        name: 'GOLANG',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '8e22a7d8-4148-4c73-80dc-8834c51fe800',
        name: 'C#',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '743145bc-c8ac-460b-a908-fdf3269d52d9',
        name: 'Vue',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'ca34b1a6-c56e-40b4-b77d-454eb971b059',
        name: 'Redis',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'hfdnmkdfg-45678ejhdf-dhfc383-3456787654',
    ideaId: 'a51c17fd-c089-448c-be7b-714bceee8109',
    initiator: usersMocks[0],
    team: null,
    marketId: '201',
    name: 'Идея для проверки',
    problem: 'null',
    description:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта',
    solution:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта',
    result: 'null',
    maxTeamSize: 7,
    customer: 'ВШЦТ',
    position: 7,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '74d9f126-e188-4d1e-abb3-d494e5e5fa89',
        name: 'Keras',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '2a03579d-9e40-4e85-a60e-6605a5a961dd',
        name: 'Scikit Learn',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
]

export const marketMocks: Market[] = [
  {
    id: '200',
    name: 'Летняя биржа 2023',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'DONE',
  },
  {
    id: '201',
    name: 'Осенняя биржа 2023',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'ACTIVE',
  },
  {
    id: '202',
    name: 'Зимняя биржа 2024',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'NEW',
  },
  {
    id: '203',
    name: 'Весенняя биржа 2024',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'NEW',
  },
]

export const usersEmailsMocks: string[] = usersMocks.map((user) => user.email)

export const usersSkillsMocks: UsersSkills[] = [
  {
    idUsers: '0',
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
  },
  {
    idUsers: '1',
    skills: [skillsMocks[1], skillsMocks[2], skillsMocks[7], skillsMocks[19]],
  },
  {
    idUsers: '2',
    skills: [skillsMocks[0], skillsMocks[1], skillsMocks[9], skillsMocks[19]],
  },
  {
    idUsers: '3',
    skills: [skillsMocks[1], skillsMocks[5], skillsMocks[6], skillsMocks[17]],
  },
  {
    idUsers: '4',
    skills: [skillsMocks[1], skillsMocks[2], skillsMocks[3], skillsMocks[16]],
  },
  {
    idUsers: '5',
    skills: [skillsMocks[0], skillsMocks[2], skillsMocks[7], skillsMocks[15]],
  },
  {
    idUsers: '6',
    skills: [skillsMocks[2], skillsMocks[2], skillsMocks[7], skillsMocks[11]],
  },
]

export const ideaMarketAdvertisementsMocks: IdeaMarketAdvertisement[] = [
  {
    id: '0',
    ideaMarketId: ideasMarketMocks[0].id,
    createdAt: '2023-03-11T11:02:17Z',

    text: 'Для выполнения данной идеи требуются только бекендеры!',
    sender: usersMocks[2],
    checkedBy: [usersMocks[2].email],
  },
  {
    id: '1',
    ideaMarketId: ideasMarketMocks[0].id,
    createdAt: '2023-03-12T11:02:17Z',

    text: 'Скоро набор закроется, быстрее подавайте заявки!',
    sender: usersMocks[2],
    checkedBy: [usersMocks[2].email],
  },
  {
    id: '2',
    ideaMarketId: ideasMarketMocks[1].id,
    createdAt: '2023-03-18T11:02:17Z',

    text: 'Требуются фронтендеры, бекендеры и желающие научиться новым компетенциям.',
    sender: usersMocks[0],
    checkedBy: [usersMocks[0].email],
  },
]

export const teamSkillsMocks: TeamSkills[] = [
  {
    teamId: '0',
    wantedSkills: [skillsMocks[0], skillsMocks[2]],
    skills: [],
  },
  {
    teamId: '1',
    wantedSkills: [
      skillsMocks[0],
      skillsMocks[1],
      skillsMocks[5],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[10],
      skillsMocks[18],
      skillsMocks[17],
      skillsMocks[16],
      skillsMocks[15],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[13],
    ],
    skills: [
      skillsMocks[0],
      skillsMocks[1],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[13],
      skillsMocks[16],
      skillsMocks[17],
      skillsMocks[18],
      skillsMocks[19],
    ],
  },
]

export const teamInvitationsMocks: TeamInvitation[] = [
  {
    id: '0',
    teamId: '1',
    userId: '3',
    email: 'maga@mail.com',
    status: 'ACCEPTED',
    firstName: 'Мамедага',
    lastName: 'Байрамов',
  },
  {
    id: '3',
    teamId: '4',
    userId: '233969a1-ac39-4ee2-be75-9866693e7336',
    email: 'kirill.vlasov.05@inbox.ru',
    status: 'NEW',
    firstName: 'Кирилл',
    lastName: 'Власов',
  },
  {
    id: '1',
    teamId: '0',
    userId: '1',
    status: 'ACCEPTED',
    email: 'timyr@mail.com',
    firstName: 'Тимур',
    lastName: 'Минязев',
  },
  {
    id: '2',
    teamId: '1',
    userId: '4',
    status: 'ACCEPTED',
    email: 'admin@mail.com',
    firstName: 'Админ',
    lastName: 'Иванов',
  },
]

export const requestsToTeamMocks: RequestToTeam[] = [
  {
    id: '1',
    teamId: '0',
    status: 'NEW',
    userId: '5',
    email: 'deins@mail.com',
    firstName: 'Денис',
    lastName: 'Денисович',
  },
  {
    id: '3',
    teamId: '5',
    userId: '233969a1-ac39-4ee2-be75-9866693e7336',
    email: 'kirill.vlasov.05@inbox.ru',
    status: 'NEW',
    firstName: 'Кирилл',
    lastName: 'Власов',
  },
  {
    id: '2',
    teamId: '1',
    userId: '3',
    status: 'NEW',
    email: 'maga@mail.com',
    firstName: 'Мамедага',
    lastName: 'Байрамов',
  },
]

export const usersGroupsMocks: UsersGroup[] = [
  {
    id: '0',
    name: 'Группа разработчиков',
    users: [...usersMocks],
    roles: ['INITIATOR'],
  },
  {
    id: '1',
    name: 'Группа экспертов',
    users: [],
    roles: ['ADMIN', 'EXPERT'],
  },
]

export const commentsMocks: Comment[] = [
  {
    id: '0',
    ideaId: '0',
    createdAt: '2023-10-20T11:02:17Z',
    sender: usersMocks[0],
    text: 'Комментарий 1',
    checkedBy: [],
  },
  {
    id: '1',
    ideaId: '0',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Комментарий 2',
    checkedBy: ['0', '1'],
  },
  {
    id: '2',
    ideaId: '1',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Требуются Frontend разработчики!',
    checkedBy: [],
  },
  {
    id: '2',
    ideaId: '2',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Скоро закроется набор!',
    checkedBy: [],
  },
]

export const ratingsMocks: Rating[] = [
  {
    id: '0',
    ideaId: '0',
    expertId: usersMocks[0].id,
    expertFirstName: usersMocks[0].firstName,
    expertLastName: usersMocks[0].lastName,
    budget: 1,
    technicalRealizability: null,
    suitability: 2,
    rating: 8 / 5,
    originality: 3,
    marketValue: 1,
    isConfirmed: false,
  },
  {
    id: '1',
    ideaId: '0',
    expertId: usersMocks[1].id,
    expertFirstName: usersMocks[1].firstName,
    expertLastName: usersMocks[1].lastName,
    budget: 2,
    technicalRealizability: 4,
    suitability: 5,
    rating: 14 / 5,
    originality: 1,
    marketValue: 2,
    isConfirmed: true,
  },
  {
    id: '2',
    ideaId: '1',
    expertId: usersMocks[0].id,
    expertFirstName: usersMocks[0].firstName,
    expertLastName: usersMocks[0].lastName,
    budget: 1,
    technicalRealizability: 1,
    suitability: 5,
    rating: null,
    originality: null,
    marketValue: null,
    isConfirmed: false,
  },
]

export const ideasMocks: Idea[] = [
  {
    id: '0',
    initiator: usersMocks[0],
    name: 'Рефактор кода',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-21T11:02:17Z',
    modifiedAt: '2023-10-26T11:02:17Z',
    status: 'ON_CONFIRMATION',
    maxTeamSize: 7,
    minTeamSize: 3,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 1,
    suitability: 1,
    preAssessment: 1,
    rating: null,
    isChecked: true,
    isActive: false,
  },
  {
    id: '1',
    initiator: usersMocks[1],
    name: 'Моя новая идея',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-24T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'ON_APPROVAL',
    maxTeamSize: 4,
    minTeamSize: 3,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 2,
    isChecked: false,
    isActive: false,
  },
  {
    id: '2',
    initiator: usersMocks[2],
    name: 'Идея 2',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'NEW',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: false,
  },
  {
    id: '3',
    initiator: usersMocks[0],
    name: 'Раскладушка',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'CONFIRMED',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: false,
  },
  {
    id: '7',
    isChecked: true,
    initiator: usersMocks[1],
    name: 'Земляника',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'CONFIRMED',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isActive: false,
  },
  {
    id: '4',
    initiator: usersMocks[2],
    name: 'Зeмляника',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'ON_MARKET',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: true,
  },
]

export const ideasSkillsMocks: IdeaSkills[] = [
  { ideaId: '0', skills: [...skillsMocks] },
  {
    ideaId: '1',
    skills: [skillsMocks[0], skillsMocks[2]],
  },
  {
    ideaId: '4',
    skills: [...skillsMocks],
  },
]

export const tasksMocks: Task[] = [
  {
    id: '0',
    sprintId: '3',
    projectId: '0',
    position: 1,
    name: 'Разработка административной панели управления задачами',
    description:
      'Необходимо создать административную панель для управления задачами, включая просмотр, создание, редактирование и удаление задач',
    initiator: usersMocks[0],
    executor: null,
    workHour: '3',
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[1], tagsMocks[5]],
    taskMovementLog: ['InBackLog'],
    status: 'NewTask',
  },
  {
    id: '1',
    sprintId: '3',
    projectId: '0',
    position: 2,
    name: 'Добавление функционала перетаскивания',
    description:
      'Расширить функционал системы задач, добавив возможность перетаскивать задачи для изменения их приоритета или порядка выполнения',
    initiator: usersMocks[1],
    executor: null,
    workHour: '1',
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[5]],
    taskMovementLog: ['InBackLog'],
    status: 'NewTask',
  },
  {
    id: '2',
    sprintId: '3',
    projectId: '0',
    position: 3,
    name: 'Интеграция с системой уведомлений',
    description:
      'Настроить интеграцию с системой уведомлений для отправки уведомлений о новых задачах, изменении статусов и прочих событиях',
    initiator: usersMocks[2],
    executor: null,
    workHour: '3',
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[1], tagsMocks[6]],
    taskMovementLog: ['InBackLog'],
    status: 'NewTask',
  },
  {
    id: '3',
    sprintId: '3',
    projectId: '0',
    name: 'Улучшение производительности',
    description:
      'Провести оптимизацию работы с базой данных и алгоритмов для обеспечения быстрой работы системы даже при большом объеме задач',
    initiator: usersMocks[0],
    executor: null,
    workHour: '3',
    position: 3,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[1], tagsMocks[8]],
    taskMovementLog: ['InBackLog'],
    status: 'NewTask',
  },
  {
    id: '4',
    sprintId: '3',
    projectId: '0',
    name: 'Внедрение системы фильтрации и поиска задач',
    description:
      'Добавить возможность фильтрации и поиска задач по различным критериям для удобства работы пользователей',
    initiator: usersMocks[1],
    executor: usersMocks[3],
    workHour: '1',
    position: 2,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[1], tagsMocks[5]],
    taskMovementLog: ['InBackLog'],
    status: 'OnModification',
    leaderComment: 'Котята, нужно прибраться!',
  },
  {
    id: '5',
    sprintId: '3',
    projectId: '0',
    name: 'Создание отчетности и статистики по выполненным задачам',
    description:
      'Разработать модуль для формирования отчетов и статистики по выполненным задачам в удобном для анализа формате',
    initiator: usersMocks[4],
    executor: usersMocks[0],
    workHour: '3',
    position: 3,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[1], tagsMocks[9]],
    taskMovementLog: ['InBackLog'],
    status: 'OnModification',
  },
  {
    id: '6',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка механизма повторяющихся задач и напоминаний',
    description:
      'Добавить возможность создания повторяющихся задач и настройки напоминаний о них',
    initiator: usersMocks[0],
    executor: usersMocks[2],
    workHour: '3',
    position: 1,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[1], tagsMocks[6]],
    taskMovementLog: ['InBackLog'],
    status: 'inProgress',
  },
  {
    id: '7',
    sprintId: '3',
    projectId: '0',
    name: 'Интеграция с календарем',
    description:
      'Настроить интеграцию с календарем для отображения задач в виде событий и синхронизации данных',
    initiator: usersMocks[0],
    executor: usersMocks[1],
    workHour: '3',
    position: 3,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[7]],
    taskMovementLog: ['InBackLog'],
    status: 'inProgress',
  },
  {
    id: '8',
    sprintId: '3',
    projectId: '0',
    name: 'Добавление комментариев к задачам',
    description:
      'Расширить функционал задач путем добавления комментариев, обсуждений и возможности прикрепления файлов',
    initiator: usersMocks[1],
    executor: usersMocks[1],
    workHour: '1',
    position: 2,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[1]],
    taskMovementLog: ['InBackLog'],
    status: 'OnVerification',
  },
  {
    id: '9',
    sprintId: '3',
    projectId: '0',
    name: 'Интеграция с системой аутентификации и авторизации',
    description:
      'Настроить интеграцию с системой аутентификации и авторизации пользователей для защиты данных и контроля доступа',
    initiator: usersMocks[0],
    executor: usersMocks[0],
    workHour: '3',
    position: 1,
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[1], tagsMocks[7], tagsMocks[10]],
    taskMovementLog: ['InBackLog'],
    status: 'Done',
  },
  {
    id: '10',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка темной темы интерфейса',
    description:
      'Создать альтернативную темную тему интерфейса для удобства пользователей',
    initiator: usersMocks[1],
    executor: usersMocks[1],
    workHour: '1',
    position: 2,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '22.01.2024',
    tag: [tagsMocks[0], tagsMocks[11], tagsMocks[5]],
    taskMovementLog: ['InBackLog'],
    status: 'Done',
  },
  {
    id: '11',
    sprintId: '3',
    projectId: '0',
    name: 'Добавление возможности прикрепления файлов',
    description:
      'Расширить функционал задач с возможностью прикрепления файлов, изображений и документов',
    initiator: usersMocks[0],
    executor: usersMocks[2],
    workHour: '3',
    position: 3,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '21.01.2024',
    tag: [tagsMocks[1]],
    taskMovementLog: ['InBackLog'],
    status: 'Done',
  },
  {
    id: '12',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка системы шаблонов задач',
    description:
      'Создать возможность создания и использования шаблонов задач для быстрого добавления типовых задач',
    initiator: usersMocks[2],
    executor: usersMocks[0],
    workHour: '3',
    position: 3,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '25.01.2024',
    tag: [tagsMocks[1]],
    taskMovementLog: ['InBackLog'],
    status: 'Done',
  },
  {
    id: '14',
    sprintId: undefined,
    projectId: '0',
    position: 1,
    name: 'Разработка мобильного приложения для работы с задачами',
    description:
      'Создание мобильного приложения для удобной работы с задачами на мобильных устройствах',
    initiator: usersMocks[1],
    executor: null,
    workHour: '8',
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[0], tagsMocks[5]],
    taskMovementLog: ['InBackLog', 'NewTask'],
    status: 'InBackLog',
  },
  {
    id: '15',
    sprintId: undefined,
    projectId: '0',
    position: 2,
    name: 'Интеграция с системой управления версиями',
    description:
      'Настроить интеграцию с системой управления версиями для контроля изменений и хранения истории задач',
    initiator: usersMocks[2],
    executor: null,
    workHour: '4',
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[1], tagsMocks[7]],
    taskMovementLog: ['InBackLog', 'NewTask'],
    status: 'InBackLog',
  },
  {
    id: '16',
    sprintId: undefined,
    projectId: '0',
    position: 3,
    name: 'Внедрение системы контроля доступа ',
    description:
      'Настройка системы контроля доступа и ролевой модели для управления правами пользователей и доступом к функционалу',
    initiator: usersMocks[4],
    executor: null,
    workHour: '2',
    startDate: '2023-09-25T11:02:17Z',
    tag: [tagsMocks[1], tagsMocks[10]],
    taskMovementLog: ['InBackLog', 'NewTask'],
    status: 'InBackLog',
  },
]

export const averageMarkMocks: AverageMark[] = [
  {
    projectId: '0',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    projectRole: 'TEAM_LEADER',
    mark: 9.9,
    tasks: [tasksMocks[9], tasksMocks[12]],
  },
  {
    projectId: '0',
    userId: '1',
    firstName: 'Иван',
    lastName: 'Иванович',
    projectRole: 'MEMBER',
    mark: 6.7,
    tasks: [tasksMocks[10]],
  },
  {
    projectId: '0',
    userId: '2',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: 7.8,
    tasks: [tasksMocks[11]],
  },
]

export const projectMocks: Project[] = [
  {
    id: '0',

    name: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    description: ideasMocks[1].description,
    customer: ideasMocks[1].customer,
    initiator: ideasMocks[1].initiator,
    team: teamsMocks[2],
    members: [
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: '2',
        email: 'alex@inbox.ru',
        firstName: 'Алексей',
        lastName: 'Князев',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'INITIATOR',
      },
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
        email: 'kirill.vlasov.05@inbox.ru',
        firstName: 'Артем',
        lastName: 'Иванов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'TEAM_LEADER',
      },
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: '0',
        email: 'timyr@mail.com',
        firstName: 'Иван',
        lastName: 'Кузнецов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: '1',
        email: 'admin@mail.com',
        firstName: 'Данил',
        lastName: 'Сафонов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
    ],

    report: {
      projectId: '0',
      marks: [averageMarkMocks[0], averageMarkMocks[1], averageMarkMocks[2]],
      report: 'Это отчет',
    },
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '',
    status: 'ACTIVE',
  },
  {
    id: '1',

    name: 'Прогнозирование закупок арматуры на основе исторических данных и обогащением доп. критериями',
    description: ideasMocks[1].description,
    customer: ideasMocks[1].customer,
    initiator: ideasMocks[1].initiator,
    team: teamsMocks[2],
    members: [
      {
        projectName: 'Табуретка',
        teamId: '0',
        teamName: 'Визитка',
        userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
        email: 'kirill.vlasov.05@inbox.ru',
        firstName: 'Кирилл',
        lastName: 'Власов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
    ],

    report: {
      projectId: '1',
      marks: [],
      report: '',
    },
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2024-01-18T11:02:17Z',
    status: 'DONE',
  },
]

export const notificationsMocks: Notification[] = [
  {
    id: '0',
    userId: '0',
    title: 'Чат 1',
    message: 'Попов(менеджер, проект 1): дедлайн завтра',
    link: null,
    isShowed: true,
    isReaded: false,
    isFavourite: false,
    createdAt: '2023-10-25T11:02:17Z',
  },
  {
    id: '1',
    userId: '1',
    title: 'Чат 2',
    message: 'Петров(менеджер, проект 2): завтра',
    link: null,
    isShowed: false,
    isReaded: false,
    isFavourite: false,
    createdAt: '2023-10-28T11:02:17Z',
  },
  {
    id: '2',
    userId: '2',
    title: 'Чат 1',
    message: 'Попов(менеджер, проект 1): дедлайн завтра',
    link: null,
    isShowed: false,
    isReaded: true,
    isFavourite: true,
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '3',
    userId: '2',
    title: 'Чат 2',
    message: 'Петров(менеджер, проект 2): дедлайн завтра',
    link: null,
    isShowed: true,
    isReaded: true,
    isFavourite: true,
    createdAt: '2023-10-30T11:02:17Z',
  },
]

export const sprintMarksMocks: SprintMarks[] = [
  {
    sprintId: '3',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    mark: undefined,
    projectRole: 'TEAM_LEADER',
    tasks: [tasksMocks[9], tasksMocks[12]],
  },
  {
    sprintId: '3',
    userId: '123714',
    firstName: 'Иван',
    lastName: 'Иванович',
    mark: undefined,
    projectRole: 'MEMBER',
    tasks: [tasksMocks[10]],
  },
  {
    sprintId: '3',
    userId: '1231231',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: undefined,
    tasks: [tasksMocks[11]],
  },
]

export const sprintMocks: Sprint[] = [
  {
    id: '0',
    projectId: projectMocks[0].id,
    name: 'Спринт 1',
    goal: 'Цель 1',
    marks: [sprintMarksMocks[0]],
    report: 'Отчет 1',
    startDate: '2023-12-26T11:02:17Z',
    finishDate: '2024-01-02T11:02:17Z',
    workingHours: '15',
    status: 'DONE',
    tasks: [],
  },
  {
    id: '1',
    projectId: projectMocks[0].id,
    name: 'Спринт 2',
    goal: 'Цель 2',
    marks: [sprintMarksMocks[1]],
    report: 'Отчет 2',
    startDate: '2024-01-03T11:02:17Z',
    finishDate: '2024-01-11T11:02:17Z',
    workingHours: '15',
    status: 'DONE',
    tasks: [],
  },
  {
    id: '2',
    projectId: projectMocks[0].id,
    name: 'Спринт 3',
    goal: 'Цель 3',
    marks: [sprintMarksMocks[2]],
    report: 'Отчет 3',
    startDate: '2024-01-12T11:02:17Z',
    finishDate: '2024-01-19T11:02:17Z',
    workingHours: '15',
    status: 'DONE',
    tasks: [],
  },
]

export const RequestTeamsMocks: RequestTeamToIdea[] = [
  {
    id: '2',
    ideaMarketId: '2',
    marketId: '201',
    teamId: '0',
    status: 'NEW',
    name: 'Первые разрабы мира',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[17],
      skillsMocks[18],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '3',
    ideaMarketId: '3',
    marketId: '201',
    teamId: '0',
    status: 'NEW',

    name: 'Чемпионы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[16],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '2',
    ideaMarketId: '1',
    marketId: '201',
    status: 'NEW',
    teamId: '2',
    name: 'Удальцы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '3',
    ideaMarketId: '1',
    marketId: '201',
    status: 'NEW',
    teamId: '3',
    name: 'Молодцы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '4',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '4',
    name: 'Хорошая компания',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '5',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '5',
    name: 'Негатив',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '6',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '6',
    name: 'Позитив',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '7',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '13',
    name: 'Смешарики',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
]

export const companiesMocks: Company[] = [
  {
    id: '0',
    name: 'ВШЦТ',
    owner: usersMocks[1],
    users: [usersMocks[2]],
  },
  {
    id: '1',
    name: 'Газпром',
    owner: usersMocks[1],
    users: [usersMocks[1]],
  },
  {
    id: '2',
    name: 'Роснефть',
    owner: usersMocks[2],
    users: [usersMocks[1]],
  },
]

export const teamsExperienceMocks: TeamExperience[] = [
  {
    teamId: teamsMocks[0].id,
    teamName: teamsMocks[0].name,
    userId: usersMocks[0].id,
    firstName: usersMocks[0].firstName,
    lastName: usersMocks[0].lastName,
    startDate: '2023-01-01T11:02:17Z',
    finishDate: null,
    hasActiveProject: teamsMocks[0].hasActiveProject,
  },
]

export const teamsProjectsMocks: ProjectMember[] = [
  {
    projectName: 'Моя новая идея',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2023-09-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Табуретка',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2023-09-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Катер',
    teamId: '2',
    teamName: 'Карасики',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: '2',
    email: 'alex@inbox.ru',
    firstName: 'Алексей',
    lastName: 'Князев',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'INITIATOR',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Артем',
    lastName: 'Иванов',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'TEAM_LEADER',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: '0',
    email: 'timyr@mail.com',
    firstName: 'Иван',
    lastName: 'Кузнецов',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: '1',
    email: 'admin@mail.com',
    firstName: 'Данил',
    lastName: 'Сафонов',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
]

export const profilesMocks: Profile[] = [
  {
    ...usersMocks[0],
    skills: [...skillsMocks],
    ideas: [ideasMocks[0], ideasMocks[1]],
    teamsExperience: teamsExperienceMocks,
    userTag: usersTelegramMocks[0].userTag,
    isUserTagVisible: true,
  },
]

export const invitationTeamToIdeaMocks: InvitationTeamToIdea[] = [
  {
    ideaId: ideasMarketMocks[0].id,
    ideaName: ideasMarketMocks[0].name,
    status: 'NEW',
    teamId: teamsMocks[0].id,
    initiatorId: ideasMarketMocks[0].initiator.id,
    id: '245vs-d52ff-d4sd-2s',
    teamName: teamsMocks[0].name,
    teamMembersCount: teamsMocks[0].membersCount,
    skills: ideasMarketMocks[0].stack,
  },
  {
    ideaId: ideasMarketMocks[1].id,
    ideaName: ideasMarketMocks[1].name,
    status: 'NEW',
    teamId: teamsMocks[1].id,
    initiatorId: ideasMarketMocks[1].initiator.id,
    id: '245vs-d52ff-d4sd-2s1',
    teamName: teamsMocks[1].name,
    teamMembersCount: teamsMocks[1].membersCount,
    skills: ideasMarketMocks[1].stack,
  },
]

export const taskMovementLogMocks: TaskMovementLog[] = [
  {
    id: '0',
    task: tasksMocks[0],
    executor: null,
    user: usersMocks[0],
    startDate: '2023-09-24T11:02:17Z',
    endDate: '2023-09-25T17:02:17Z',
    taskStatus: 'NewTask',
  },
  {
    id: '1',
    task: tasksMocks[0],
    executor: usersMocks[1],
    user: usersMocks[1],
    startDate: '2023-09-25T17:02:17Z',
    endDate: '2023-09-30T10:11:17Z',
    taskStatus: 'inProgress',
  },
  {
    id: '2',
    task: tasksMocks[0],
    executor: usersMocks[1],
    user: usersMocks[1],
    startDate: '2023-09-30T10:11:17Z',
    endDate: '2023-10-02T18:00:17Z',
    taskStatus: 'OnVerification',
  },
  {
    id: '3',
    task: tasksMocks[0],
    executor: usersMocks[1],
    user: usersMocks[0],
    startDate: '2023-10-02T18:31:17Z',
    endDate: '',
    taskStatus: 'Done',
  },
]
