import { User, UserTelegram } from '@Domain/User'
import { Profile } from '@Domain/Profile'
import UsersGroup from '@Domain/UsersGroup'
import Company from '@Domain/Company'
import UsersSkills from '@Domain/UsersSkills'
import { Skill } from '@Domain/Skill'
import { Idea, IdeaSkills, Rating } from '@Domain/Idea'
import Comment from '@Domain/Comment'
import {
  RequestToTeam,
  Team,
  TeamExperience,
  TeamInvitation,
  TeamMember,
  TeamSkills,
} from '@Domain/Team'
import Notification from '@Domain/Notification'
import { IdeaMarket, IdeaMarketAdvertisement } from '@Domain/IdeaMarket'
import { Market } from '@Domain/Market'
import { RequestTeamToIdea } from '@Domain/RequestTeamToIdea'
import { Project, ProjectMember } from '@Domain/Project'
import { Tag } from '@Domain/Tag'

export const usersMocks: User[] = [
  {
    id: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    token: '10296538',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    roles: [
      'INITIATOR',
      'PROJECT_OFFICE',
      'EXPERT',
      'ADMIN',
      'MEMBER',
      'TEAM_LEADER',
    ],
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '1',
    token: '1',
    email: '1@mail.com',
    firstName: 'Иван',
    lastName: 'Иванович',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '2',
    token: '059182',
    email: '2@mail.com',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '3',
    token: '163097',
    email: '3@mail.com',
    firstName: 'Владелец',
    lastName: 'Владелец',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '4',
    token: '8755764',
    email: '4@mail.com',
    firstName: 'Винрит',
    lastName: 'Загрев',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '5',
    token: '836444',
    email: '5@mail.com',
    firstName: 'Версаль',
    lastName: 'Кустерман',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
  },
  // {
  //   id: '6',
  //   token: '6745354',
  //   email: '6@mail.com',
  //   firstName: 'Дмитрий',
  //   lastName: 'Амонов',
  //   roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN'],
  // },
]

export const usersTelegramMocks: UserTelegram[] = [
  {
    userId: usersMocks[0].id,
    userTag: 'baobao',
    chatId: '0',
    isVisible: true,
  },
  {
    userId: usersMocks[1].id,
    userTag: '@chipichipi',
    chatId: '5',
    isVisible: false,
  },
  {
    userId: usersMocks[1].id,
    userTag: '@chapachapa',
    chatId: null,
    isVisible: true,
  },
]

export const tagsMocks: Tag[] = [
  {
    id: '0',
    name: 'Фронтенд',
    color: '#cd1d1d',
    confirmed: true,
  },
  {
    id: '1',
    name: 'Бекенд',
    color: '#279b74',
    confirmed: true,
  },
  {
    id: '2',
    name: 'Рефактор',
    color: '#cc8c33',
    confirmed: false,
  },
]

export const skillsMocks: Skill[] = [
  {
    id: '0',
    name: 'JavaScript',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '1',
    name: 'Python',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '2',
    name: 'Rust',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '3',
    name: 'Swift',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '4',
    name: 'Kotlin',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '5',
    name: 'Go',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '6',
    name: 'React JS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '7',
    name: 'C++',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '8',
    name: 'VueJS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '9',
    name: 'Angular',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '10',
    name: 'NodeJS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '11',
    name: 'Docker',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '12',
    name: 'Git',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '13',
    name: 'Grafana',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '14',
    name: 'Elasticsearch',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '15',
    name: 'MongoDB',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '16',
    name: 'PostgreSQL',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '17',
    name: 'MySQL',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '18',
    name: 'SQLite',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '19',
    name: 'Redis',
    type: 'DATABASE',
    confirmed: true,
  },
]

export const teamMembersMocks: TeamMember[] = [
  {
    id: '277922d4-e08a-430b-9b94-949dc32681b4',
    teamId: '1',
    userId: '1',
    email: 'timyr@mail.com',
    firstName: 'Тимур',
    lastName: 'Минязев',
    skills: [],
  },
  {
    id: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    teamId: '1',
    userId: '0',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    skills: [],
  },
  {
    id: '2',
    teamId: '0',
    userId: '3',
    email: 'admin@mail.com',
    firstName: 'Админ',
    lastName: 'Иванов',
    skills: [],
  },
  {
    id: '3',
    teamId: '1',
    userId: '4',
    email: 'deins@mail.com',
    firstName: 'Денис',
    lastName: 'Денисович',
    skills: [],
  },
]

export const teamsMocks: Team[] = [
  {
    id: '0',
    name: 'Визитка',
    closed: true,
    hasActiveProject: true,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 4,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [teamMembersMocks[0], teamMembersMocks[2], teamMembersMocks[3]],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
  },
  {
    id: '1',
    name: 'Кактус',
    closed: false,
    hasActiveProject: false,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 4,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [teamMembersMocks[0], teamMembersMocks[2], teamMembersMocks[3]],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
  },
  {
    id: '2',
    name: 'Карасики',
    closed: false,
    hasActiveProject: false,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 4,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [
      teamMembersMocks[0],
      teamMembersMocks[1],
      teamMembersMocks[2],
      teamMembersMocks[3],
    ],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
  },
]

export const ideasMarketMocks: IdeaMarket[] = [
  {
    id: 'dfaedabe-2b3b-44e7-851e-35c9c6409869',
    initiator: {
      id: '1',
      email: 'barbakovom@tyuiu.ru',
      lastName: 'Барбаков',
      firstName: 'Олег',
    } as User,
    team: teamsMocks[0],
    marketId: '201',
    name: 'Цифровой помощник сотрудника приемной комиссии университета',
    problem: 'null',
    description: 'null',
    solution:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта ',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 7,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '74d9f126-e188-4d1e-abb3-d494e5e5fa89',
        name: 'Keras',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '2a03579d-9e40-4e85-a60e-6605a5a961dd',
        name: 'Scikit Learn',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
    ],
    status: 'PROJECT',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: '279b3fbf-de63-426f-bf9f-0c01ea19706b',
    initiator: {
      id: '2bafebe0-9514-43e0-badf-548388dfa2d4',
      email: 'warkingzar@gmail.com',
      lastName: 'Зайко',
      firstName: 'Антон',
    } as User,
    team: null,
    marketId: '201',
    name: 'PW Technology: Интерактивное виртуальное образование с 3D тренажерами',
    problem: 'null',
    description: 'null',
    solution:
      'Разработка проекта по обучению людей взаимодействию с оборудованием в игровой форме, где каждый пользователь сможет примерить на себя роль нефтяника, электрика, строителя и других профессий, требующих специальных навыков и знаний.\n',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 8,
    stack: [
      {
        id: '31ea96a6-4da7-4618-a9f7-0f2531c35033',
        name: 'Unreal Engine GameMode',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: '15bc47fb-e894-4698-b86f-52be31fd7064',
        name: 'C++',
        type: 'LANGUAGE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'c2d8b869-2731-4c37-b0de-17c1950a770f',
    initiator: {
      id: '09e6884f-65c5-4cd5-98f1-2f4ebb5823c0',
      email: 'l.a.nikiforova@tmn3.etagi.com',
      lastName: 'Никифорова',
      firstName: 'Любовь',
    } as User,
    team: null,
    marketId: '201',
    name: 'EMetrics.Viewer',
    problem: 'null',
    description: 'null',
    solution:
      'WEB-приложение (конкретная реализация выбирается разработчиками в рамках стэка React|Vue, NodeJS|Python)\nИспользование существующих у заказчика оперативных и аналитических БД в том числе тестовых.\nИспользование VPN (предоставляется заказчиком) для подключения к ресурсам заказчика с машин разработчиков.',
    result: 'null',
    maxTeamSize: 5,
    customer: 'null',
    position: 9,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'd908579e-4528-4268-bb7f-e072c5dc3f4d',
        name: 'GOLANG',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '8e22a7d8-4148-4c73-80dc-8834c51fe800',
        name: 'C#',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '743145bc-c8ac-460b-a908-fdf3269d52d9',
        name: 'Vue',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'ca34b1a6-c56e-40b4-b77d-454eb971b059',
        name: 'Redis',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'a51c17fd-c089-448c-be7b-714bceee8109',
    initiator: {
      id: '12c1534d-c6d1-4515-b531-ea380d75b772',
      email: 'd.shirokov@unlim.group',
      lastName: 'Широков',
      firstName: 'Дмитрий',
    } as User,
    team: null,
    marketId: '2',
    name: 'Расчет строительных материалов. ',
    problem: 'null',
    description: 'null',
    solution:
      'Система, которая позволяет указать размерные характеристики объекта строительства и\\или работ, выбрать требуемый материал и получить расчет количества этих материалов.\nПродумать систему придется в рамках реализации проекта.',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 10,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'd908579e-4528-4268-bb7f-e072c5dc3f4d',
        name: 'GOLANG',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '8e22a7d8-4148-4c73-80dc-8834c51fe800',
        name: 'C#',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '743145bc-c8ac-460b-a908-fdf3269d52d9',
        name: 'Vue',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'ca34b1a6-c56e-40b4-b77d-454eb971b059',
        name: 'Redis',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'hfdnmkdfg-45678ejhdf-dhfc383-3456787654',
    initiator: usersMocks[0],
    team: teamsMocks[0],
    marketId: '201',
    name: 'Идея для проверки',
    problem: 'null',
    description:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта',
    solution:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта',
    result: 'null',
    maxTeamSize: 7,
    customer: 'ВШЦТ',
    position: 7,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '74d9f126-e188-4d1e-abb3-d494e5e5fa89',
        name: 'Keras',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '2a03579d-9e40-4e85-a60e-6605a5a961dd',
        name: 'Scikit Learn',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_CLOSED',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
]

export const marketMocks: Market[] = [
  {
    id: '200',
    name: 'Летняя биржа 2023',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'DONE',
  },
  {
    id: '201',
    name: 'Осенняя биржа 2023',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'ACTIVE',
  },
  {
    id: '202',
    name: 'Зимняя биржа 2024',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'NEW',
  },
  {
    id: '203',
    name: 'Весенняя биржа 2024',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'NEW',
  },
]

export const usersEmailsMocks: string[] = usersMocks.map((user) => user.email)

export const usersSkillsMocks: UsersSkills[] = [
  {
    idUsers: '0',
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
  },
  {
    idUsers: '1',
    skills: [skillsMocks[1], skillsMocks[2], skillsMocks[7], skillsMocks[19]],
  },
  {
    idUsers: '2',
    skills: [skillsMocks[0], skillsMocks[1], skillsMocks[9], skillsMocks[19]],
  },
  {
    idUsers: '3',
    skills: [skillsMocks[1], skillsMocks[5], skillsMocks[6], skillsMocks[17]],
  },
  {
    idUsers: '4',
    skills: [skillsMocks[1], skillsMocks[2], skillsMocks[3], skillsMocks[16]],
  },
  {
    idUsers: '5',
    skills: [skillsMocks[0], skillsMocks[2], skillsMocks[7], skillsMocks[15]],
  },
  {
    idUsers: '6',
    skills: [skillsMocks[2], skillsMocks[2], skillsMocks[7], skillsMocks[11]],
  },
]

export const ideaMarketAdvertisementsMocks: IdeaMarketAdvertisement[] = [
  {
    id: '0',
    ideaMarketId: ideasMarketMocks[0].id,
    createdAt: '2023-03-11T11:02:17Z',

    text: 'Для выполнения данной идеи требуются только бекендеры!',
    sender: usersMocks[2],
    checkedBy: [usersMocks[2].email],
  },
  {
    id: '1',
    ideaMarketId: ideasMarketMocks[0].id,
    createdAt: '2023-03-12T11:02:17Z',

    text: 'Скоро набор закроется, быстрее подавайте заявки!',
    sender: usersMocks[2],
    checkedBy: [usersMocks[2].email],
  },
  {
    id: '2',
    ideaMarketId: ideasMarketMocks[1].id,
    createdAt: '2023-03-18T11:02:17Z',

    text: 'Требуются фронтендеры, бекендеры и желающие научиться новым компетенциям.',
    sender: usersMocks[0],
    checkedBy: [usersMocks[0].email],
  },
]

export const teamSkillsMocks: TeamSkills[] = [
  {
    teamId: '0',
    wantedSkills: [skillsMocks[0], skillsMocks[2]],
    skills: [],
  },
  {
    teamId: '1',
    wantedSkills: [
      skillsMocks[0],
      skillsMocks[1],
      skillsMocks[5],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[10],
      skillsMocks[18],
      skillsMocks[17],
      skillsMocks[16],
      skillsMocks[15],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[13],
    ],
    skills: [
      skillsMocks[0],
      skillsMocks[1],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[13],
      skillsMocks[16],
      skillsMocks[17],
      skillsMocks[18],
      skillsMocks[19],
    ],
  },
]

export const teamInvitationsMocks: TeamInvitation[] = [
  {
    id: '0',
    teamId: '1',
    userId: '3',
    email: 'maga@mail.com',
    status: 'ACCEPTED',
    firstName: 'Мамедага',
    lastName: 'Байрамов',
  },
  {
    id: '3',
    teamId: '4',
    userId: '233969a1-ac39-4ee2-be75-9866693e7336',
    email: 'kirill.vlasov.05@inbox.ru',
    status: 'NEW',
    firstName: 'Кирилл',
    lastName: 'Власов',
  },
  {
    id: '1',
    teamId: '0',
    userId: '1',
    status: 'ACCEPTED',
    email: 'timyr@mail.com',
    firstName: 'Тимур',
    lastName: 'Минязев',
  },
  {
    id: '2',
    teamId: '1',
    userId: '4',
    status: 'ACCEPTED',
    email: 'admin@mail.com',
    firstName: 'Админ',
    lastName: 'Иванов',
  },
]

export const requestsToTeamMocks: RequestToTeam[] = [
  {
    id: '1',
    teamId: '0',
    status: 'NEW',
    userId: '5',
    email: 'deins@mail.com',
    firstName: 'Денис',
    lastName: 'Денисович',
  },
  {
    id: '3',
    teamId: '5',
    userId: '233969a1-ac39-4ee2-be75-9866693e7336',
    email: 'kirill.vlasov.05@inbox.ru',
    status: 'NEW',
    firstName: 'Кирилл',
    lastName: 'Власов',
  },
  {
    id: '2',
    teamId: '1',
    userId: '3',
    status: 'NEW',
    email: 'maga@mail.com',
    firstName: 'Мамедага',
    lastName: 'Байрамов',
  },
]

export const usersGroupsMocks: UsersGroup[] = [
  {
    id: '0',
    name: 'Группа разработчиков',
    users: [...usersMocks],
    roles: ['INITIATOR'],
  },
  {
    id: '1',
    name: 'Группа экспертов',
    users: [],
    roles: ['ADMIN', 'EXPERT'],
  },
]

export const commentsMocks: Comment[] = [
  {
    id: '0',
    ideaId: '0',
    createdAt: '2023-10-20T11:02:17Z',
    sender: usersMocks[0],
    text: 'Комментарий 1',
    checkedBy: [],
  },
  {
    id: '1',
    ideaId: '0',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Комментарий 2',
    checkedBy: ['0', '1'],
  },
  {
    id: '2',
    ideaId: '1',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Требуются Frontend разработчики!',
    checkedBy: [],
  },
  {
    id: '2',
    ideaId: '2',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Скоро закроется набор!',
    checkedBy: [],
  },
]

export const ratingsMocks: Rating[] = [
  {
    id: '0',
    ideaId: '0',
    expertId: usersMocks[0].id,
    expertFirstName: usersMocks[0].firstName,
    expertLastName: usersMocks[0].lastName,
    budget: 1,
    technicalRealizability: null,
    suitability: 2,
    rating: 8 / 5,
    originality: 3,
    marketValue: 1,
    isConfirmed: false,
  },
  {
    id: '1',
    ideaId: '0',
    expertId: usersMocks[1].id,
    expertFirstName: usersMocks[1].firstName,
    expertLastName: usersMocks[1].lastName,
    budget: 2,
    technicalRealizability: 4,
    suitability: 5,
    rating: 14 / 5,
    originality: 1,
    marketValue: 2,
    isConfirmed: true,
  },
  {
    id: '2',
    ideaId: '1',
    expertId: usersMocks[0].id,
    expertFirstName: usersMocks[0].firstName,
    expertLastName: usersMocks[0].lastName,
    budget: 1,
    technicalRealizability: 1,
    suitability: 5,
    rating: null,
    originality: null,
    marketValue: null,
    isConfirmed: false,
  },
]

export const ideasMocks: Idea[] = [
  {
    id: '0',
    initiator: usersMocks[0],
    name: 'Рефактор кода',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-21T11:02:17Z',
    modifiedAt: '2023-10-26T11:02:17Z',
    status: 'ON_CONFIRMATION',
    maxTeamSize: 7,
    minTeamSize: 3,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 1,
    suitability: 1,
    preAssessment: 1,
    rating: null,
    isChecked: true,
    isActive: false,
  },
  {
    id: '1',
    initiator: usersMocks[1],
    name: 'Моя новая идея',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-24T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'ON_APPROVAL',
    maxTeamSize: 4,
    minTeamSize: 3,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 2,
    isChecked: false,
    isActive: false,
  },
  {
    id: '2',
    initiator: usersMocks[2],
    name: 'Идея 2',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'NEW',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: false,
  },
  {
    id: '3',
    initiator: usersMocks[0],
    name: 'Раскладушка',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'CONFIRMED',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: false,
  },
  {
    id: '7',
    isChecked: true,
    initiator: usersMocks[1],
    name: 'Земляника',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'CONFIRMED',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isActive: false,
  },
  {
    id: '4',
    initiator: usersMocks[2],
    name: 'Зeмляника',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'ON_MARKET',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: true,
  },
]

export const ideasSkillsMocks: IdeaSkills[] = [
  { ideaId: '0', skills: [...skillsMocks] },
  {
    ideaId: '1',
    skills: [skillsMocks[0], skillsMocks[2]],
  },
  {
    ideaId: '4',
    skills: [...skillsMocks],
  },
]

export const projectMocks: Project[] = [
  {
    id: '0',

    name: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    description: ideasMocks[1].description,
    customer: ideasMocks[1].customer,
    initiator: ideasMocks[1].initiator,
    team: teamsMocks[2],
    members: [
      {
        projectName: 'Моя новая идея',
        teamId: '0',
        teamName: 'Визитка',
        userId: '2',
        email: 'alex@inbox.ru',
        firstName: 'Алексей',
        lastName: 'Князев',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'INITIATOR',
      },
      {
        projectName: 'Моя новая идея',
        teamId: '0',
        teamName: 'Визитка',
        userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
        email: 'kirill.vlasov.05@inbox.ru',
        firstName: 'Артем',
        lastName: 'Иванов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'TEAM_LEADER',
      },
      {
        projectName: 'Моя новая идея',
        teamId: '0',
        teamName: 'Визитка',
        userId: '0',
        email: 'timyr@mail.com',
        firstName: 'Иван',
        lastName: 'Кузнецов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
      {
        projectName: 'Моя новая идея',
        teamId: '0',
        teamName: 'Визитка',
        userId: '1',
        email: 'admin@mail.com',
        firstName: 'Данил',
        lastName: 'Сафонов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
    ],

    logs: [],
    report: '',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '',
    status: 'ACTIVE',
  },
  {
    id: '1',

    name: 'Прогнозирование закупок арматуры на основе исторических данных и обогащением доп. критериями',
    description: ideasMocks[1].description,
    customer: ideasMocks[1].customer,
    initiator: ideasMocks[1].initiator,
    team: teamsMocks[2],
    members: [
      {
        projectName: 'Табуретка',
        teamId: '0',
        teamName: 'Визитка',
        userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
        email: 'kirill.vlasov.05@inbox.ru',
        firstName: 'Кирилл',
        lastName: 'Власов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
    ],

    logs: [],
    report: '',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2024-01-18T11:02:17Z',
    status: 'DONE',
  },
]

export const notificationsMocks: Notification[] = [
  {
    id: '0',
    userId: '0',
    title: 'Чат 1',
    message: 'Попов(менеджер, проект 1): дедлайн завтра',
    link: null,
    isShowed: true,
    isReaded: false,
    isFavourite: false,
    createdAt: '2023-10-25T11:02:17Z',
  },
  {
    id: '1',
    userId: '1',
    title: 'Чат 2',
    message: 'Петров(менеджер, проект 2): завтра',
    link: null,
    isShowed: false,
    isReaded: false,
    isFavourite: false,
    createdAt: '2023-10-28T11:02:17Z',
  },
  {
    id: '2',
    userId: '2',
    title: 'Чат 1',
    message: 'Попов(менеджер, проект 1): дедлайн завтра',
    link: null,
    isShowed: false,
    isReaded: true,
    isFavourite: true,
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '3',
    userId: '2',
    title: 'Чат 2',
    message: 'Петров(менеджер, проект 2): дедлайн завтра',
    link: null,
    isShowed: true,
    isReaded: true,
    isFavourite: true,
    createdAt: '2023-10-30T11:02:17Z',
  },
]

export const RequestTeamsMocks: RequestTeamToIdea[] = [
  {
    id: '2',
    ideaMarketId: '2',
    marketId: '201',
    teamId: '0',
    status: 'NEW',
    name: 'Первые разрабы мира',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[17],
      skillsMocks[18],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '3',
    ideaMarketId: '3',
    marketId: '201',
    teamId: '0',
    status: 'NEW',

    name: 'Чемпионы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[16],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '2',
    ideaMarketId: '1',
    marketId: '201',
    status: 'NEW',
    teamId: '2',
    name: 'Удальцы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '3',
    ideaMarketId: '1',
    marketId: '201',
    status: 'NEW',
    teamId: '3',
    name: 'Молодцы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '4',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '4',
    name: 'Хорошая компания',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '5',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '5',
    name: 'Негатив',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '6',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '6',
    name: 'Позитив',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '7',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '13',
    name: 'Смешарики',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
]

export const companiesMocks: Company[] = [
  {
    id: '0',
    name: 'ВШЦТ',
    owner: usersMocks[1],
    users: [usersMocks[2]],
  },
  {
    id: '1',
    name: 'Газпром',
    owner: usersMocks[1],
    users: [usersMocks[1]],
  },
  {
    id: '2',
    name: 'Роснефть',
    owner: usersMocks[2],
    users: [usersMocks[1]],
  },
]

export const teamsExperienceMocks: TeamExperience[] = [
  {
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-01-01T11:02:17Z',
    finishDate: '2023-03-14T11:02:17Z',
    hasActiveProject: false,
  },
  {
    teamId: '2',
    teamName: 'Карасики',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-03-14T11:02:17Z',
    finishDate: '2023-09-20T11:02:17Z',
    hasActiveProject: false,
  },
  {
    teamId: '1',
    teamName: 'Кактус',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-20T11:02:17Z',
    finishDate: '2023-11-25T11:02:17Z',
    hasActiveProject: false,
  },
  {
    teamId: '2',
    teamName: 'Карасики',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-11-25T11:02:17Z',
    finishDate: null,
    hasActiveProject: true,
  },
]

export const teamsProjectsMocks: ProjectMember[] = [
  {
    projectName: 'Моя новая идея',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2023-09-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Табуретка',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2023-09-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Катер',
    teamId: '2',
    teamName: 'Карасики',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '',
    projectRole: 'MEMBER',
  },
]

export const profilesMocks: Profile[] = [
  {
    ...usersMocks[0],
    skills: [...skillsMocks],
    ideas: [ideasMocks[0], ideasMocks[1]],
    teamsExperience: teamsExperienceMocks,
    teamsProjects: teamsProjectsMocks,
    userTag: usersTelegramMocks[0].userTag,
    isUserTagVisible: true,
  },
]
