import { User, UserTelegram } from '@Domain/User'
import { Profile } from '@Domain/Profile'
import UsersGroup from '@Domain/UsersGroup'
import Company from '@Domain/Company'
import UsersSkills from '@Domain/UsersSkills'
import { Skill } from '@Domain/Skill'
import { Idea, IdeaSkills, Rating } from '@Domain/Idea'
import Comment from '@Domain/Comment'
import {
  RequestToTeam,
  courseEnum,
  Team,
  TeamExperience,
  TeamInvitation,
  TeamMember,
  TeamSkills,
  TeamTags,
} from '@Domain/Team'
import Notification from '@Domain/Notification'
import { IdeaMarket, IdeaMarketAdvertisement } from '@Domain/IdeaMarket'
import { Market } from '@Domain/Market'
import { RequestTeamToIdea } from '@Domain/RequestTeamToIdea'
import {
  TaskMovementLog,
  Project,
  ProjectMember,
  Sprint,
  SprintMarks,
  Task,
} from '@Domain/Project'
import { Tag } from '@Domain/Tag'
import { InvitationTeamToIdea } from '@Domain/InvitationTeamToIdea'
import { AverageMark } from '@Domain/ReportProjectMembers'
import {
  Indicator,
  Quest,
  QuestTemplate,
  QuestTemplateShort,
  QuestResult,
  QuestStat as QuestCollapseData,
  TeamQuestStat as MembersCollapseData,
  UsersQuestStat,
  IndicatorCategory,
  QuestResultWrapper,
} from '@Domain/Quest'
import { Test, TestQuestion, TestAnswer, TestResult } from '@Domain/Test'

export const usersMocks: User[] = [
  {
    id: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    token: '10296538',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    roles: [
      'INITIATOR',
      'PROJECT_OFFICE',
      'EXPERT',
      'ADMIN',
      'MEMBER',
      'TEAM_LEADER',
      'TEACHER',
    ],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '1111111111',
    studyGroup: 'AAAA-22-1',
  },
  {
    id: '126288eb-9d4d-4074-9c87-6e4a566ef8f9',
    token: '1',
    email: '1@mail.com',
    firstName: 'Иван',
    lastName: 'Иванович',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER', 'TEACHER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '22222222222',
    studyGroup: 'BBBB-22-1',
  },
  {
    id: '2',
    token: '059182',
    email: '2@mail.com',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER', 'TEACHER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '33333333333',
    studyGroup: 'CCCC-22-1',
  },
  {
    id: '3',
    token: '163097',
    email: '3@mail.com',
    firstName: 'Владелец',
    lastName: 'Владелец',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER', 'TEACHER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '44444444444',
    studyGroup: 'DDDD-22-1',
  },
  {
    id: '4',
    token: '8755764',
    email: '4@mail.com',
    firstName: 'Винрит',
    lastName: 'Загрев',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '55555555555',
    studyGroup: 'EEEE-22-1',
  },
  {
    id: '5',
    token: '836444',
    email: '5@mail.com',
    firstName: 'Версаль',
    lastName: 'Кустерман',
    roles: ['INITIATOR', 'PROJECT_OFFICE', 'EXPERT', 'ADMIN', 'MEMBER'],
    createdAt: '2023-10-20T11:02:17Z',
    telephone: '66666666666',
    studyGroup: 'FFFF-22-1',
  },
]

export const usersTelegramMocks: UserTelegram[] = [
  {
    userId: usersMocks[0].id,
    userTag: 'baobao',
    chatId: '0',
    isVisible: true,
  },
  {
    userId: usersMocks[1].id,
    userTag: '@chipichipi',
    chatId: '5',
    isVisible: false,
  },
  {
    userId: usersMocks[1].id,
    userTag: '@chapachapa',
    chatId: null,
    isVisible: true,
  },
]

export const tagsMocks: Tag[] = [
  {
    id: '0',
    name: 'Фронтенд',
    color: '#0D6EFD',
    confirmed: true,
  },
  {
    id: '1',
    name: 'Бекенд',
    color: '#FFA800',
    confirmed: true,
  },
  {
    id: '2',
    name: 'Рефактор',
    color: '#AEA709',
    confirmed: true,
  },
  {
    id: '3',
    name: 'Изучения',
    color: '#13C63A',
    confirmed: true,
  },
  {
    id: '4',
    name: 'Бегать',
    color: '#BB2D3B',
    confirmed: false,
  },
  {
    id: '5',
    name: 'UI/UX',
    color: '#6fa8dc',
    confirmed: true,
  },
  {
    id: '6',
    name: 'Уведомления',
    color: '#6aa84f',
    confirmed: true,
  },
  {
    id: '7',
    name: 'Интеграция',
    color: '#674ea7',
    confirmed: true,
  },
  {
    id: '8',
    name: 'Оптимизация',
    color: '#cc0000',
    confirmed: true,
  },
  {
    id: '9',
    name: 'Статистика',
    color: '#76a5af',
    confirmed: true,
  },
  {
    id: '10',
    name: 'Безопасность',
    color: '#660000',
    confirmed: true,
  },
  {
    id: '11',
    name: 'Дизайн',
    color: '#8fce00',
    confirmed: true,
  },
]

export const skillsMocks: Skill[] = [
  {
    id: '0',
    name: 'JavaScript',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '1',
    name: 'Python',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '2',
    name: 'Rust',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '3',
    name: 'Swift',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '4',
    name: 'Kotlin',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '5',
    name: 'Go',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '6',
    name: 'React JS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '7',
    name: 'C++',
    type: 'LANGUAGE',
    confirmed: true,
  },
  {
    id: '8',
    name: 'VueJS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '9',
    name: 'Angular',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '10',
    name: 'NodeJS',
    type: 'FRAMEWORK',
    confirmed: true,
  },
  {
    id: '11',
    name: 'Docker',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '12',
    name: 'Git',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '13',
    name: 'Grafana',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '14',
    name: 'Elasticsearch',
    type: 'DEVOPS',
    confirmed: true,
  },
  {
    id: '15',
    name: 'MongoDB',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '16',
    name: 'PostgreSQL',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '17',
    name: 'MySQL',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '18',
    name: 'SQLite',
    type: 'DATABASE',
    confirmed: true,
  },
  {
    id: '19',
    name: 'Redis',
    type: 'DATABASE',
    confirmed: true,
  },
]

export const teamMembersMocks: TeamMember[] = [
  {
    id: '277922d4-e08a-430b-9b94-949dc32681b4',
    teamId: '1',
    userId: '1',
    email: 'timyr@mail.com',
    firstName: 'Тимур',
    lastName: 'Минязев',
    skills: [],
  },
  {
    id: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    teamId: '1',
    userId: '0',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    skills: [],
  },
  {
    id: '2',
    teamId: '0',
    userId: '3',
    email: 'admin@mail.com',
    firstName: 'Админ',
    lastName: 'Иванов',
    skills: [],
  },
  {
    id: '3',
    teamId: '1',
    userId: '4',
    email: 'deins@mail.com',
    firstName: 'Денис',
    lastName: 'Денисович',
    skills: [],
  },
]

export const teamTagsMocks: TeamTags[] = [
  {
    studyGroups: ['ИИП-22-1', 'ИСТНб-21'],
    studyCourses: [courseEnum.first, courseEnum.second],
  },
  {
    studyGroups: ['ИИПб-23-1', 'АСОИУ-22-1'],
    studyCourses: [courseEnum.second],
  },
  {
    studyGroups: ['ИСТНб-21-2', 'АСОИУ-20-1'],
    studyCourses: [courseEnum.third, courseEnum.fourth],
  },
]

export const teamsMocks: Team[] = [
  {
    id: '1',
    name: 'Визитка',
    closed: true,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 2,
    owner: teamMembersMocks[1],
    leader: teamMembersMocks[1],
    members: [
      teamMembersMocks[0],
      teamMembersMocks[1],
      teamMembersMocks[2],
      teamMembersMocks[3],
    ],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
    tags: teamTagsMocks[0],
    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
    hasActiveProject: true,
    isAcceptedToIdea: true,
    StatusQuest: false,
  },
  {
    id: '2',
    name: 'Кактус',
    closed: false,
    hasActiveProject: false,
    createdAt: '2023-10-20T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 5,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [teamMembersMocks[0], teamMembersMocks[2], teamMembersMocks[3]],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],

    tags: teamTagsMocks[1],
    StatusQuest: false,
    isAcceptedToIdea: true,

    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
  },
  {
    id: '3',
    name: 'Карасики',
    closed: false,
    createdAt: '2023-10-10T11:02:17Z',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    membersCount: 6,
    owner: teamMembersMocks[0],
    leader: teamMembersMocks[0],
    members: [teamMembersMocks[0], teamMembersMocks[2], teamMembersMocks[3]],
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],

    tags: teamTagsMocks[2],

    wantedSkills: [skillsMocks[0], skillsMocks[11], skillsMocks[16]],
    isRefused: false,
    hasActiveProject: false,
    isAcceptedToIdea: true,

    StatusQuest: false,
  },
]

export const ideasMarketMocks: IdeaMarket[] = [
  {
    id: 'dfaedabe-2b3b-44e7-851e-35c9c6409869',
    ideaId: 'dfaedabe-2b3b-44e7-851e-35c9c6409869',
    initiator: usersMocks[0],
    team: null,
    marketId: '201',
    name: 'Цифровой помощник сотрудника приемной комиссии университета',
    problem: 'null',
    description: 'null',
    solution:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта ',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 7,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '74d9f126-e188-4d1e-abb3-d494e5e5fa89',
        name: 'Keras',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '2a03579d-9e40-4e85-a60e-6605a5a961dd',
        name: 'Scikit Learn',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: '279b3fbf-de63-426f-bf9f-0c01ea19706b',
    ideaId: '279b3fbf-de63-426f-bf9f-0c01ea19706b',
    initiator: {
      id: '2bafebe0-9514-43e0-badf-548388dfa2d4',
      email: 'warkingzar@gmail.com',
      lastName: 'Зайко',
      firstName: 'Антон',
    } as User,
    team: null,
    marketId: '201',
    name: 'PW Technology: Интерактивное виртуальное образование с 3D тренажерами',
    problem: 'null',
    description: 'null',
    solution:
      'Разработка проекта по обучению людей взаимодействию с оборудованием в игровой форме, где каждый пользователь сможет примерить на себя роль нефтяника, электрика, строителя и других профессий, требующих специальных навыков и знаний.\n',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 8,
    stack: [
      {
        id: '31ea96a6-4da7-4618-a9f7-0f2531c35033',
        name: 'Unreal Engine GameMode',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: '15bc47fb-e894-4698-b86f-52be31fd7064',
        name: 'C++',
        type: 'LANGUAGE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'c2d8b869-2731-4c37-b0de-17c1950a770f',
    ideaId: 'c2d8b869-2731-4c37-b0de-17c1950a770f',
    initiator: {
      id: '09e6884f-65c5-4cd5-98f1-2f4ebb5823c0',
      email: 'l.a.nikiforova@tmn3.etagi.com',
      lastName: 'Никифорова',
      firstName: 'Любовь',
    } as User,
    team: null,
    marketId: '201',
    name: 'EMetrics.Viewer',
    problem: 'null',
    description: 'null',
    solution:
      'WEB-приложение (конкретная реализация выбирается разработчиками в рамках стэка React|Vue, NodeJS|Python)\nИспользование существующих у заказчика оперативных и аналитических БД в том числе тестовых.\nИспользование VPN (предоставляется заказчиком) для подключения к ресурсам заказчика с машин разработчиков.',
    result: 'null',
    maxTeamSize: 5,
    customer: 'null',
    position: 9,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'd908579e-4528-4268-bb7f-e072c5dc3f4d',
        name: 'GOLANG',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '8e22a7d8-4148-4c73-80dc-8834c51fe800',
        name: 'C#',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '743145bc-c8ac-460b-a908-fdf3269d52d9',
        name: 'Vue',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'ca34b1a6-c56e-40b4-b77d-454eb971b059',
        name: 'Redis',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'a51c17fd-c089-448c-be7b-714bceee8109',
    ideaId: 'a51c17fd-c089-448c-be7b-714bceee8109',
    initiator: {
      id: '12c1534d-c6d1-4515-b531-ea380d75b772',
      email: 'd.shirokov@unlim.group',
      lastName: 'Широков',
      firstName: 'Дмитрий',
    } as User,
    team: null,
    marketId: '2',
    name: 'Расчет строительных материалов. ',
    problem: 'null',
    description: 'null',
    solution:
      'Система, которая позволяет указать размерные характеристики объекта строительства и\\или работ, выбрать требуемый материал и получить расчет количества этих материалов.\nПродумать систему придется в рамках реализации проекта.',
    result: 'null',
    maxTeamSize: 7,
    customer: 'null',
    position: 10,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'd908579e-4528-4268-bb7f-e072c5dc3f4d',
        name: 'GOLANG',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '8e22a7d8-4148-4c73-80dc-8834c51fe800',
        name: 'C#',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '743145bc-c8ac-460b-a908-fdf3269d52d9',
        name: 'Vue',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: 'b74f4f1c-1d09-47b7-b8d0-e8d6e1ac95d5',
        name: 'Git',
        type: 'DEVOPS',
        confirmed: true,
      },
      {
        id: 'ca34b1a6-c56e-40b4-b77d-454eb971b059',
        name: 'Redis',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
  {
    id: 'hfdnmkdfg-45678ejhdf-dhfc383-3456787654',
    ideaId: 'a51c17fd-c089-448c-be7b-714bceee8109',
    initiator: usersMocks[0],
    team: null,
    marketId: '201',
    name: 'Идея для проверки',
    problem: 'null',
    description:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта',
    solution:
      'Разработать web приложение для прогнозирования предпочтительного направления обучения поступающих , прогноза успеваемости и успешности с применением технологий машинного обучения и искусственного интеллекта',
    result: 'null',
    maxTeamSize: 7,
    customer: 'ВШЦТ',
    position: 7,
    stack: [
      {
        id: 'b629e3cb-c544-4b7c-8fa6-679df5fffc9c',
        name: 'Python',
        type: 'LANGUAGE',
        confirmed: true,
      },
      {
        id: '74d9f126-e188-4d1e-abb3-d494e5e5fa89',
        name: 'Keras',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '2a03579d-9e40-4e85-a60e-6605a5a961dd',
        name: 'Scikit Learn',
        type: 'FRAMEWORK',
        confirmed: true,
      },
      {
        id: '5165bc7b-1495-4540-9517-2f1f4a54f273',
        name: 'PostgreSQL',
        type: 'DATABASE',
        confirmed: true,
      },
      {
        id: '0c0c65ee-aba3-4ba4-80ed-cf1ebe26da36',
        name: 'Docker',
        type: 'DEVOPS',
        confirmed: true,
      },
    ],
    status: 'RECRUITMENT_IS_OPEN',
    requests: 0,
    acceptedRequests: 0,
    isFavorite: false,
  },
]

export const marketMocks: Market[] = [
  {
    id: '200',
    name: 'Летняя биржа 2023',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'DONE',
  },
  {
    id: '201',
    name: 'Осенняя биржа 2023',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'ACTIVE',
  },
  {
    id: '202',
    name: 'Зимняя биржа 2024',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'NEW',
  },
  {
    id: '203',
    name: 'Весенняя биржа 2024',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    status: 'NEW',
  },
]

export const usersEmailsMocks: string[] = usersMocks.map((user) => user.email)

export const usersSkillsMocks: UsersSkills[] = [
  {
    idUsers: '0',
    skills: [skillsMocks[0], skillsMocks[4], skillsMocks[6], skillsMocks[9]],
  },
  {
    idUsers: '1',
    skills: [skillsMocks[1], skillsMocks[2], skillsMocks[7], skillsMocks[19]],
  },
  {
    idUsers: '2',
    skills: [skillsMocks[0], skillsMocks[1], skillsMocks[9], skillsMocks[19]],
  },
  {
    idUsers: '3',
    skills: [skillsMocks[1], skillsMocks[5], skillsMocks[6], skillsMocks[17]],
  },
  {
    idUsers: '4',
    skills: [skillsMocks[1], skillsMocks[2], skillsMocks[3], skillsMocks[16]],
  },
  {
    idUsers: '5',
    skills: [skillsMocks[0], skillsMocks[2], skillsMocks[7], skillsMocks[15]],
  },
  {
    idUsers: '6',
    skills: [skillsMocks[2], skillsMocks[2], skillsMocks[7], skillsMocks[11]],
  },
]

export const ideaMarketAdvertisementsMocks: IdeaMarketAdvertisement[] = [
  {
    id: '0',
    ideaMarketId: ideasMarketMocks[0].id,
    createdAt: '2023-03-11T11:02:17Z',

    text: 'Для выполнения данной идеи требуются только бекендеры!',
    sender: usersMocks[2],
    checkedBy: [usersMocks[2].email],
  },
  {
    id: '1',
    ideaMarketId: ideasMarketMocks[0].id,
    createdAt: '2023-03-12T11:02:17Z',

    text: 'Скоро набор закроется, быстрее подавайте заявки!',
    sender: usersMocks[2],
    checkedBy: [usersMocks[2].email],
  },
  {
    id: '2',
    ideaMarketId: ideasMarketMocks[1].id,
    createdAt: '2023-03-18T11:02:17Z',

    text: 'Требуются фронтендеры, бекендеры и желающие научиться новым компетенциям.',
    sender: usersMocks[0],
    checkedBy: [usersMocks[0].email],
  },
]

export const teamSkillsMocks: TeamSkills[] = [
  {
    teamId: '0',
    wantedSkills: [skillsMocks[0], skillsMocks[2]],
    skills: [],
  },
  {
    teamId: '1',
    wantedSkills: [
      skillsMocks[0],
      skillsMocks[1],
      skillsMocks[5],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[10],
      skillsMocks[18],
      skillsMocks[17],
      skillsMocks[16],
      skillsMocks[15],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[13],
    ],
    skills: [
      skillsMocks[0],
      skillsMocks[1],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[13],
      skillsMocks[16],
      skillsMocks[17],
      skillsMocks[18],
      skillsMocks[19],
    ],
  },
]

export const teamInvitationsMocks: TeamInvitation[] = [
  {
    id: '0',
    teamId: '1',
    userId: '3',
    email: 'maga@mail.com',
    status: 'ACCEPTED',
    firstName: 'Мамедага',
    lastName: 'Байрамов',
  },
  {
    id: '3',
    teamId: '4',
    userId: '233969a1-ac39-4ee2-be75-9866693e7336',
    email: 'kirill.vlasov.05@inbox.ru',
    status: 'NEW',
    firstName: 'Кирилл',
    lastName: 'Власов',
  },
  {
    id: '1',
    teamId: '0',
    userId: '1',
    status: 'ACCEPTED',
    email: 'timyr@mail.com',
    firstName: 'Тимур',
    lastName: 'Минязев',
  },
  {
    id: '2',
    teamId: '1',
    userId: '4',
    status: 'ACCEPTED',
    email: 'admin@mail.com',
    firstName: 'Админ',
    lastName: 'Иванов',
  },
]

export const requestsToTeamMocks: RequestToTeam[] = [
  {
    id: '1',
    teamId: '0',
    status: 'NEW',
    userId: '5',
    email: 'deins@mail.com',
    firstName: 'Денис',
    lastName: 'Денисович',
  },
  {
    id: '3',
    teamId: '5',
    userId: '233969a1-ac39-4ee2-be75-9866693e7336',
    email: 'kirill.vlasov.05@inbox.ru',
    status: 'NEW',
    firstName: 'Кирилл',
    lastName: 'Власов',
  },
  {
    id: '2',
    teamId: '1',
    userId: '3',
    status: 'NEW',
    email: 'maga@mail.com',
    firstName: 'Мамедага',
    lastName: 'Байрамов',
  },
]

export const usersGroupsMocks: UsersGroup[] = [
  {
    id: '0',
    name: 'Группа разработчиков',
    users: [...usersMocks],
    roles: ['INITIATOR'],
  },
  {
    id: '1',
    name: 'Группа экспертов',
    users: [],
    roles: ['ADMIN', 'EXPERT'],
  },
]

export const commentsMocks: Comment[] = [
  {
    id: '0',
    ideaId: '0',
    createdAt: '2023-10-20T11:02:17Z',
    sender: usersMocks[0],
    text: 'Комментарий 1',
    checkedBy: [],
  },
  {
    id: '1',
    ideaId: '0',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Комментарий 2',
    checkedBy: ['0', '1'],
  },
  {
    id: '2',
    ideaId: '1',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Требуются Frontend разработчики!',
    checkedBy: [],
  },
  {
    id: '2',
    ideaId: '2',
    createdAt: '2023-10-21T11:02:17Z',
    sender: usersMocks[0],
    text: 'Скоро закроется набор!',
    checkedBy: [],
  },
]

export const ratingsMocks: Rating[] = [
  {
    id: '0',
    ideaId: '0',
    expertId: usersMocks[0].id,
    expertFirstName: usersMocks[0].firstName,
    expertLastName: usersMocks[0].lastName,
    budget: 1,
    technicalRealizability: null,
    suitability: 2,
    rating: 8 / 5,
    originality: 3,
    marketValue: 1,
    isConfirmed: false,
  },
  {
    id: '1',
    ideaId: '0',
    expertId: usersMocks[1].id,
    expertFirstName: usersMocks[1].firstName,
    expertLastName: usersMocks[1].lastName,
    budget: 2,
    technicalRealizability: 4,
    suitability: 5,
    rating: 14 / 5,
    originality: 1,
    marketValue: 2,
    isConfirmed: true,
  },
  {
    id: '2',
    ideaId: '1',
    expertId: usersMocks[0].id,
    expertFirstName: usersMocks[0].firstName,
    expertLastName: usersMocks[0].lastName,
    budget: 1,
    technicalRealizability: 1,
    suitability: 5,
    rating: null,
    originality: null,
    marketValue: null,
    isConfirmed: false,
  },
]

export const ideasMocks: Idea[] = [
  {
    id: '0',
    initiator: usersMocks[0],
    name: 'Рефактор кода',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-21T11:02:17Z',
    modifiedAt: '2023-10-26T11:02:17Z',
    status: 'ON_CONFIRMATION',
    maxTeamSize: 7,
    minTeamSize: 3,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 1,
    suitability: 1,
    preAssessment: 1,
    rating: null,
    isChecked: true,
    isActive: false,
  },
  {
    id: '1',
    initiator: usersMocks[1],
    name: 'Моя новая идея',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-24T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'ON_APPROVAL',
    maxTeamSize: 4,
    minTeamSize: 3,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 2,
    isChecked: false,
    isActive: false,
  },
  {
    id: '2',
    initiator: usersMocks[2],
    name: 'Идея 2',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'NEW',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: false,
  },
  {
    id: '3',
    initiator: usersMocks[0],
    name: 'Раскладушка',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'CONFIRMED',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: false,
  },
  {
    id: '7',
    isChecked: true,
    initiator: usersMocks[1],
    name: 'Земляника',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'CONFIRMED',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isActive: false,
  },
  {
    id: '4',
    initiator: usersMocks[2],
    name: 'Зeмляника',
    problem:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    solution:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    result:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aperiam delectus possimus, voluptates quo accusamus? Consequatur, quasi rem temporibus blanditiis delectus aliquid officia aut, totam incidunt reiciendis eaque laborum fugiat!',
    createdAt: '2023-10-25T11:02:17Z',
    modifiedAt: '2023-10-25T11:02:17Z',
    status: 'ON_MARKET',
    maxTeamSize: 5,
    minTeamSize: 5,
    customer: 'ВШЦТ',
    contactPerson: 'ВШЦТ',
    experts: null,
    projectOffice: null,
    budget: 4,
    suitability: 3,
    preAssessment: 4,
    rating: 4,
    isChecked: false,
    isActive: true,
  },
]

export const ideasSkillsMocks: IdeaSkills[] = [
  { ideaId: '0', skills: [...skillsMocks] },
  {
    ideaId: '1',
    skills: [skillsMocks[0], skillsMocks[2]],
  },
  {
    ideaId: '4',
    skills: [...skillsMocks],
  },
]

export const tasksMocks: Task[] = [
  {
    id: '0',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка административной панели управления задачами',
    description:
      'Необходимо создать административную панель для управления задачами, включая просмотр, создание, редактирование и удаление задач',
    initiator: usersMocks[0],
    executor: null,
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[1], tagsMocks[5]],
    status: 'NewTask',
  },
  {
    id: '1',
    sprintId: '3',
    projectId: '0',
    name: 'Добавление функционала перетаскивания',
    description:
      'Расширить функционал системы задач, добавив возможность перетаскивать задачи для изменения их приоритета или порядка выполнения',
    initiator: usersMocks[1],
    executor: null,
    workHour: 1,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[5]],
    status: 'NewTask',
  },
  {
    id: '2',
    sprintId: '3',
    projectId: '0',
    name: 'Интеграция с системой уведомлений',
    description:
      'Настроить интеграцию с системой уведомлений для отправки уведомлений о новых задачах, изменении статусов и прочих событиях',
    initiator: usersMocks[2],
    executor: null,
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[1], tagsMocks[6]],
    status: 'NewTask',
  },
  {
    id: '3',
    sprintId: '3',
    projectId: '0',
    name: 'Улучшение производительности',
    description:
      'Провести оптимизацию работы с базой данных и алгоритмов для обеспечения быстрой работы системы даже при большом объеме задач',
    initiator: usersMocks[0],
    executor: null,
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[1], tagsMocks[8]],
    status: 'NewTask',
  },
  {
    id: '4',
    sprintId: '3',
    projectId: '0',
    name: 'Внедрение системы фильтрации и поиска задач',
    description:
      'Добавить возможность фильтрации и поиска задач по различным критериям для удобства работы пользователей',
    initiator: usersMocks[1],
    executor: usersMocks[3],
    workHour: 1,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[1], tagsMocks[5]],
    status: 'OnModification',
    leaderComment: 'Котята, нужно прибраться!',
  },
  {
    id: '5',
    sprintId: '3',
    projectId: '0',
    name: 'Создание отчетности и статистики по выполненным задачам',
    description:
      'Разработать модуль для формирования отчетов и статистики по выполненным задачам в удобном для анализа формате',
    initiator: usersMocks[4],
    executor: usersMocks[0],
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[1], tagsMocks[9]],
    status: 'OnModification',
  },
  {
    id: '6',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка механизма повторяющихся задач и напоминаний',
    description:
      'Добавить возможность создания повторяющихся задач и настройки напоминаний о них',
    initiator: usersMocks[0],
    executor: usersMocks[2],
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[1], tagsMocks[6]],
    status: 'InProgress',
  },
  {
    id: '7',
    sprintId: '3',
    projectId: '0',
    name: 'Интеграция с календарем',
    description:
      'Настроить интеграцию с календарем для отображения задач в виде событий и синхронизации данных',
    initiator: usersMocks[0],
    executor: usersMocks[1],
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[7]],
    status: 'InProgress',
  },
  {
    id: '8',
    sprintId: '3',
    projectId: '0',
    name: 'Добавление комментариев к задачам',
    description:
      'Расширить функционал задач путем добавления комментариев, обсуждений и возможности прикрепления файлов',
    initiator: usersMocks[1],
    executor: usersMocks[1],
    workHour: 1,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[1]],
    status: 'OnVerification',
  },
  {
    id: '9',
    sprintId: '3',
    projectId: '0',
    name: 'Интеграция с системой аутентификации и авторизации',
    description:
      'Настроить интеграцию с системой аутентификации и авторизации пользователей для защиты данных и контроля доступа',
    initiator: usersMocks[0],
    executor: usersMocks[0],
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2024-01-25T11:02:17Z',
    tags: [tagsMocks[1], tagsMocks[7], tagsMocks[10]],
    status: 'Done',
  },
  {
    id: '10',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка темной темы интерфейса',
    description:
      'Создать альтернативную темную тему интерфейса для удобства пользователей',
    initiator: usersMocks[1],
    executor: usersMocks[1],
    workHour: 1,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2024-01-22T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[11], tagsMocks[5]],
    status: 'Done',
  },
  {
    id: '11',
    sprintId: '3',
    projectId: '0',
    name: 'Добавление возможности прикрепления файлов',
    description:
      'Расширить функционал задач с возможностью прикрепления файлов, изображений и документов',
    initiator: usersMocks[0],
    executor: usersMocks[2],
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2024-01-21T11:02:17Z',
    tags: [tagsMocks[1]],
    status: 'Done',
  },
  {
    id: '12',
    sprintId: '3',
    projectId: '0',
    name: 'Разработка системы шаблонов задач',
    description:
      'Создать возможность создания и использования шаблонов задач для быстрого добавления типовых задач',
    initiator: usersMocks[2],
    executor: usersMocks[0],
    workHour: 3,
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2024-01-25T11:02:17Z',
    tags: [tagsMocks[1]],
    status: 'Done',
  },
  {
    id: '14',
    sprintId: undefined,
    projectId: '0',
    position: 1,
    name: 'Разработка мобильного приложения для работы с задачами',
    description:
      'Создание мобильного приложения для удобной работы с задачами на мобильных устройствах',
    initiator: usersMocks[1],
    executor: null,
    workHour: 8,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[0], tagsMocks[5]],
    status: 'InBackLog',
  },
  {
    id: '15',
    sprintId: undefined,
    projectId: '0',
    position: 2,
    name: 'Интеграция с системой управления версиями',
    description:
      'Настроить интеграцию с системой управления версиями для контроля изменений и хранения истории задач',
    initiator: usersMocks[2],
    executor: null,
    workHour: 4,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[1], tagsMocks[7]],
    status: 'InBackLog',
  },
  {
    id: '16',
    sprintId: undefined,
    projectId: '0',
    position: 3,
    name: 'Внедрение системы контроля доступа ',
    description:
      'Настройка системы контроля доступа и ролевой модели для управления правами пользователей и доступом к функционалу',
    initiator: usersMocks[4],
    executor: null,
    workHour: 2,
    startDate: '2023-09-25T11:02:17Z',
    tags: [tagsMocks[1], tagsMocks[10]],
    status: 'InBackLog',
  },
]

export const averageMarkMocks: AverageMark[] = [
  {
    projectId: '0',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    projectRole: 'TEAM_LEADER',
    mark: 9.9,
    tasks: [tasksMocks[9], tasksMocks[12]],
  },
  {
    projectId: '0',
    userId: '1',
    firstName: 'Иван',
    lastName: 'Иванович',
    projectRole: 'MEMBER',
    mark: 6.7,
    tasks: [tasksMocks[10]],
  },
  {
    projectId: '0',
    userId: '2',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: 7.8,
    tasks: [tasksMocks[11]],
  },
  {
    projectId: '0',
    userId: '2',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: 7.8,
    tasks: [tasksMocks[11]],
  },
  {
    projectId: '0',
    userId: '2',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: 7.8,
    tasks: [tasksMocks[11]],
  },
  {
    projectId: '0',
    userId: '2',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: 7.8,
    tasks: [tasksMocks[11]],
  },
]

export const projectMocks: Project[] = [
  {
    id: '0',
    ideaId: '0',
    name: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    description: ideasMocks[1].description,
    customer: ideasMocks[1].customer,
    initiator: ideasMocks[1].initiator,
    team: teamsMocks[2],
    members: [
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: '2',
        email: 'alex@inbox.ru',
        firstName: 'Алексей',
        lastName: 'Князев',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'INITIATOR',
      },
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
        email: 'kirill.vlasov.05@inbox.ru',
        firstName: 'Артем',
        lastName: 'Иванов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'TEAM_LEADER',
      },
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: '0',
        email: 'timyr@mail.com',
        firstName: 'Иван',
        lastName: 'Кузнецов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
      {
        projectName:
          'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
        teamId: '0',
        teamName: 'Визитка',
        userId: '1',
        email: 'admin@mail.com',
        firstName: 'Данил',
        lastName: 'Сафонов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
    ],

    report: {
      projectId: '0',
      marks: [averageMarkMocks[0], averageMarkMocks[1], averageMarkMocks[2]],
      report: 'Это отчет',
    },
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '',
    status: 'ACTIVE',
  },
  {
    id: '1',
    ideaId: '1',
    name: 'Прогнозирование закупок арматуры на основе исторических данных и обогащением доп. критериями',
    description: ideasMocks[1].description,
    customer: ideasMocks[1].customer,
    initiator: ideasMocks[1].initiator,
    team: teamsMocks[2],
    members: [
      {
        projectName: 'Табуретка',
        teamId: '0',
        teamName: 'Визитка',
        userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
        email: 'kirill.vlasov.05@inbox.ru',
        firstName: 'Кирилл',
        lastName: 'Власов',
        startDate: '2023-10-25T11:02:17Z',
        finishDate: '2023-10-25T11:02:17Z',
        projectRole: 'MEMBER',
      },
    ],

    report: {
      projectId: '1',
      marks: [],
      report: '',
    },
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2024-01-18T11:02:17Z',
    status: 'DONE',
  },
]

export const notificationsMocks: Notification[] = [
  {
    id: '0',
    userId: '0',
    title: 'Чат 1',
    message: 'Попов(менеджер, проект 1): дедлайн завтра',
    link: null,
    isShowed: true,
    isReaded: false,
    isFavourite: false,
    createdAt: '2023-10-25T11:02:17Z',
  },
  {
    id: '1',
    userId: '1',
    title: 'Чат 2',
    message: 'Петров(менеджер, проект 2): завтра',
    link: null,
    isShowed: false,
    isReaded: false,
    isFavourite: false,
    createdAt: '2023-10-28T11:02:17Z',
  },
  {
    id: '2',
    userId: '2',
    title: 'Чат 1',
    message: 'Попов(менеджер, проект 1): дедлайн завтра',
    link: null,
    isShowed: false,
    isReaded: true,
    isFavourite: true,
    createdAt: '2023-10-20T11:02:17Z',
  },
  {
    id: '3',
    userId: '2',
    title: 'Чат 2',
    message: 'Петров(менеджер, проект 2): дедлайн завтра',
    link: null,
    isShowed: true,
    isReaded: true,
    isFavourite: true,
    createdAt: '2023-10-30T11:02:17Z',
  },
]

export const sprintMarksMocks: SprintMarks[] = [
  {
    sprintId: '3',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    firstName: 'Кирилл',
    lastName: 'Власов',
    mark: undefined,
    projectRole: 'TEAM_LEADER',
    countCompletedTasks: 2,
  },
  {
    sprintId: '3',
    userId: '123714',
    firstName: 'Иван',
    lastName: 'Иванович',
    mark: undefined,
    projectRole: 'MEMBER',
    countCompletedTasks: 2,
  },
  {
    sprintId: '3',
    userId: '1231231',
    firstName: 'Менеджер',
    lastName: 'Менеджер',
    projectRole: 'MEMBER',
    mark: undefined,
    countCompletedTasks: 2,
  },
]

export const sprintMocks: Sprint[] = [
  {
    id: '0',
    projectId: projectMocks[0].id,
    name: 'Спринт 1',
    goal: 'Цель 1',
    report: 'Отчет 1',
    startDate: '2023-12-26T11:02:17Z',
    finishDate: '2024-01-02T11:02:17Z',
    workingHours: 15,
    status: 'DONE',
    tasks: [],
  },
  {
    id: '1',
    projectId: projectMocks[0].id,
    name: 'Спринт 2',
    goal: 'Цель 2',
    report: 'Отчет 2',
    startDate: '2024-01-03T11:02:17Z',
    finishDate: '2024-01-11T11:02:17Z',
    workingHours: 15,
    status: 'DONE',
    tasks: [],
  },
  {
    id: '2',
    projectId: projectMocks[0].id,
    name: 'Спринт 3',
    goal: 'Цель 3',
    report: 'Отчет 3',
    startDate: '2024-01-12T11:02:17Z',
    finishDate: '2024-01-19T11:02:17Z',
    workingHours: 15,
    status: 'DONE',
    tasks: [],
  },
  {
    id: '3',
    projectId: projectMocks[0].id,
    name: 'Проектировка скрама',
    goal: 'Цель 4',
    report: 'Отчет 4',
    startDate: '2024-01-20T11:02:17Z',
    finishDate: '2024-01-27T11:02:17Z',
    workingHours: 20,
    status: 'ACTIVE',
    tasks: tasksMocks.filter(({ status }) => status !== 'InBackLog'),
  },
]

export const RequestTeamsMocks: RequestTeamToIdea[] = [
  {
    id: '2',
    ideaMarketId: '2',
    marketId: '201',
    teamId: '0',
    status: 'NEW',
    name: 'Первые разрабы мира',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[17],
      skillsMocks[18],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '3',
    ideaMarketId: '3',
    marketId: '201',
    teamId: '0',
    status: 'NEW',

    name: 'Чемпионы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[11],
      skillsMocks[12],
      skillsMocks[16],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '2',
    ideaMarketId: '1',
    marketId: '201',
    status: 'NEW',
    teamId: '2',
    name: 'Удальцы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '3',
    ideaMarketId: '1',
    marketId: '201',
    status: 'NEW',
    teamId: '3',
    name: 'Молодцы',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '4',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '4',
    name: 'Хорошая компания',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '5',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '5',
    name: 'Негатив',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '6',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '6',
    name: 'Позитив',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
  {
    id: '7',
    ideaMarketId: '2',
    marketId: '201',
    status: 'NEW',
    teamId: '13',
    name: 'Смешарики',
    membersCount: 4,
    skills: [
      skillsMocks[0],
      skillsMocks[2],
      skillsMocks[3],
      skillsMocks[4],
      skillsMocks[6],
      skillsMocks[7],
      skillsMocks[8],
      skillsMocks[9],
      skillsMocks[11],
    ],
    letter:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorbeatae ipsum dicta omnis adipisci magni autem eos quisquam doloresmaxime. Dignissimos cum nulla consequatur accusantium distinctioaut. Velit, assumenda porro!',
  },
]

export const companiesMocks: Company[] = [
  {
    id: '0',
    name: 'ВШЦТ',
    owner: usersMocks[1],
    users: [usersMocks[2]],
  },
  {
    id: '1',
    name: 'Газпром',
    owner: usersMocks[1],
    users: [usersMocks[1]],
  },
  {
    id: '2',
    name: 'Роснефть',
    owner: usersMocks[2],
    users: [usersMocks[1]],
  },
]

export const teamsExperienceMocks: TeamExperience[] = [
  {
    teamId: teamsMocks[0].id,
    teamName: teamsMocks[0].name,
    userId: usersMocks[0].id,
    firstName: usersMocks[0].firstName,
    lastName: usersMocks[0].lastName,
    startDate: '2023-01-01T11:02:17Z',
    finishDate: null,
    hasActiveProject: teamsMocks[0].hasActiveProject,
  },
]

export const teamsProjectsMocks: ProjectMember[] = [
  {
    projectName: 'Моя новая идея',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2023-09-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Табуретка',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '2023-09-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Катер',
    teamId: '2',
    teamName: 'Карасики',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Кирилл',
    lastName: 'Власов',
    startDate: '2023-09-25T11:02:17Z',
    finishDate: '',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: '2',
    email: 'alex@inbox.ru',
    firstName: 'Алексей',
    lastName: 'Князев',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'INITIATOR',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: 'ffc1b25e-8a65-4cb2-8808-6eba443acec8',
    email: 'kirill.vlasov.05@inbox.ru',
    firstName: 'Артем',
    lastName: 'Иванов',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'TEAM_LEADER',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: '0',
    email: 'timyr@mail.com',
    firstName: 'Иван',
    lastName: 'Кузнецов',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
  {
    projectName: 'Чат-бот в telegram для запросов и обращений к HR вне системы 1С',
    teamId: '0',
    teamName: 'Визитка',
    userId: '1',
    email: 'admin@mail.com',
    firstName: 'Данил',
    lastName: 'Сафонов',
    startDate: '2023-10-25T11:02:17Z',
    finishDate: '2023-10-25T11:02:17Z',
    projectRole: 'MEMBER',
  },
]

export const profilesMocks: Profile[] = [
  {
    ...usersMocks[0],
    skills: [...skillsMocks],
    ideas: [ideasMocks[0], ideasMocks[1]],
    teams: teamsExperienceMocks,
    userTag: usersTelegramMocks[0].userTag,
    isUserTagVisible: true,
  },
]

export const invitationTeamToIdeaMocks: InvitationTeamToIdea[] = [
  {
    ideaId: ideasMarketMocks[0].id,
    ideaName: ideasMarketMocks[0].name,
    status: 'NEW',
    teamId: teamsMocks[0].id,
    initiatorId: ideasMarketMocks[0].initiator.id,
    id: '245vs-d52ff-d4sd-2s',
    teamName: teamsMocks[0].name,
    teamMembersCount: teamsMocks[0].membersCount,
    skills: ideasMarketMocks[0].stack,
  },
  {
    ideaId: ideasMarketMocks[1].id,
    ideaName: ideasMarketMocks[1].name,
    status: 'NEW',
    teamId: teamsMocks[1].id,
    initiatorId: ideasMarketMocks[1].initiator.id,
    id: '245vs-d52ff-d4sd-2s1',
    teamName: teamsMocks[1].name,
    teamMembersCount: teamsMocks[1].membersCount,
    skills: ideasMarketMocks[1].stack,
  },
]

export const taskMovementLogMocks: TaskMovementLog[] = [
  {
    id: '0',
    task: tasksMocks[0],
    executor: null,
    user: usersMocks[0],
    startDate: '2023-09-24T11:02:17Z',
    endDate: '2023-09-25T17:02:17Z',
    wastedTime: '02ч 31мин',
    status: 'NewTask',
  },
  {
    id: '1',
    task: tasksMocks[0],
    executor: usersMocks[1],
    user: usersMocks[1],
    startDate: '2023-09-25T17:02:17Z',
    endDate: '2023-09-30T10:11:17Z',
    wastedTime: '02ч 31мин',
    status: 'InProgress',
  },
  {
    id: '2',
    task: tasksMocks[0],
    executor: usersMocks[1],
    user: usersMocks[1],
    startDate: '2023-09-30T10:11:17Z',
    endDate: '2023-10-02T18:00:17Z',
    wastedTime: '02ч 31мин',
    status: 'OnVerification',
  },
  {
    id: '3',
    task: tasksMocks[0],
    executor: usersMocks[1],
    user: usersMocks[0],
    startDate: '2023-10-02T18:31:17Z',
    endDate: '',
    wastedTime: '',
    status: 'Done',
  },
]

export const questsShortMocks: QuestTemplateShort[] = [
  {
    idQuestTemplate: '1',
    available: true,
    name: 'Опрос компетенций',
  },
  {
    idQuestTemplate: '2',
    available: true,
    name: 'Опрос компетенций',
  },
]

export const indicatorCategories: IndicatorCategory[] = [
  { idCategory: '1', name: 'soft' },
  { idCategory: '2', name: 'hard' },
]

export const indicatorsMocks: Indicator[] = [
  {
    id: '1',
    name: 'Как вам отношения в команде?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '2',
    name: 'Как вам профессионализм команды?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'TEAM_LEADER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '3',
    name: 'Каков ваш взгляд на коммуникацию с этим членом команды?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '4',
    name: 'Как оцениваете общение в команде?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'TEAM_LEADER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '5',
    name: 'Какие ваши мысли о навыках команды?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '6',
    name: 'Как оцените атмосферу в коллективе?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'INITIATOR',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '7',
    name: 'Что вы думаете о взаимодействии с этим коллегой?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'TEACHER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '8',
    name: 'Ваше мнение о компетентности команды?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '9',
    name: 'Что вы думаете о взаимодействии внутри группы?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '10',
    name: 'Как воспринимаете атмосферу в команде?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '11',
    name: 'Как вы оцениваете профессионализм коллег?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '12',
    name: 'Ваш взгляд на взаимодействие с коллегами?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '13',
    name: 'Что вы думаете о внутренних отношениях в команде?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '14',
    name: 'Как вы оцениваете профессиональные навыки команды?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '15',
    name: 'Ваше мнение о взаимодействии с коллегами?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '16',
    name: 'Что вы думаете о взаимодействии в команде?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '17',
    name: 'Как вы оцениваете атмосферу в команде?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '18',
    name: 'Что вы думаете о профессионализме команды?',
    answers: ['Хорошо', 'Не очень'],
    type: 'TEAM',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
  {
    id: '19',
    name: 'Ваш взгляд на взаимодействие с коллегой?',
    answers: ['Хорошо', 'Не очень'],
    type: 'MEMBER',
    role: 'MEMBER',
    idCategory: indicatorCategories[0].idCategory,
    categoryName: indicatorCategories[0].name,
    visible: true,
  },
]

export const QuestsTemplateMocks: QuestTemplate[] = [
  {
    idQuestTemplate: questsShortMocks[0].idQuestTemplate,
    available: questsShortMocks[0].available,
    name: questsShortMocks[0].name,
    description: 'Весенний опрос 2024 посвящен весне и птичкам',
    indicators: indicatorsMocks.slice(0, 7),
  },
  {
    idQuestTemplate: questsShortMocks[1].idQuestTemplate,
    available: questsShortMocks[1].available,
    name: questsShortMocks[1].name,
    description: 'Осенний опрос 2024 посвящен весне и птичкам',
    indicators: indicatorsMocks.slice(0, 7),
  },
]

export const QuestsMocks: Quest[] = [
  {
    idQuest: '4',
    idQuestTemplate: QuestsTemplateMocks[0].idQuestTemplate!,
    idTeams: [
      { id: teamsMocks[0].id },
      { id: teamsMocks[1].id },
      { id: teamsMocks[2].id },
    ],
    name: 'Весенний опрос 2024',
    startAt: '28.04.2024',
    endAt: '28.05.2024',
    available: true,
    percent: '22',
    passed: false,
  },
  {
    idQuest: '3',
    idQuestTemplate: QuestsTemplateMocks[1].idQuestTemplate!,
    idTeams: [{ id: teamsMocks[0].id }],
    name: 'Осенний опрос 2023',
    startAt: '28.11.2023',
    endAt: '28.12.2023',
    available: true,
    percent: '77',
    passed: true,
  },
  {
    idQuest: '2',
    idQuestTemplate: QuestsTemplateMocks[0].idQuestTemplate!,
    idTeams: [{ id: teamsMocks[0].id }],
    name: 'Весенний опрос 2023',
    startAt: '28.04.2023',
    endAt: '28.05.2023',
    available: true,
    percent: '65',
    passed: true,
  },
  {
    idQuest: '1',
    idQuestTemplate: QuestsTemplateMocks[1].idQuestTemplate!,
    idTeams: [{ id: teamsMocks[0].id }],
    name: 'Осенний опрос 2022',
    startAt: '28.11.2022',
    endAt: '28.12.2022',
    available: false,
    percent: '50',
    passed: false,
  },
]

export const resultsMocks: QuestResultWrapper = {
  results: [
    {
      idResult: '8',
      idIndicator: indicatorsMocks[0].id,
      idQuest: QuestsMocks[0].idQuest,
      idFromUser: usersMocks[0].id,
      value: '4',
    },
    {
      idResult: '7',
      idIndicator: indicatorsMocks[1].id,
      idQuest: QuestsMocks[0].idQuest,
      idFromUser: usersMocks[0].id,
      idToUser: '',
      value: '',
    },
    ...teamsMocks[0].members.map((member): QuestResult => {
      return {
        idResult: '33' + member.userId,
        idIndicator: indicatorsMocks[2].id,
        idQuest: QuestsMocks[0].idQuest,
        idFromUser: usersMocks[0].id,
        idToUser: member.userId,
        value: '',
      }
    }),
    {
      idResult: '4',
      idIndicator: indicatorsMocks[0].id,
      idQuest: QuestsMocks[0].idQuest,
      idFromUser: usersMocks[0].id,
      idToUser: '',
      value: '',
    },
    {
      idResult: '3',
      idIndicator: indicatorsMocks[1].id,
      idQuest: QuestsMocks[0].idQuest,
      idFromUser: usersMocks[0].id,
      idToUser: '',
      value: '',
    },
    ...teamsMocks[0].members.map((member): QuestResult => {
      return {
        idResult: '22' + member.userId,
        idIndicator: indicatorsMocks[2].id,
        idQuest: QuestsMocks[0].idQuest,
        idFromUser: usersMocks[0].id,
        idToUser: member.userId,
        value: '',
      }
    }),
  ],
}
export const usersQuestStatMocks: UsersQuestStat[] = [
  {
    id: usersMocks[0].id,
    name: `${usersMocks[0].firstName} ${usersMocks[0].lastName}`,
    progress: false,
  },
  {
    id: usersMocks[1].id,
    name: `${usersMocks[1].firstName} ${usersMocks[0].lastName}`,
    progress: false,
  },
  {
    id: usersMocks[2].id,
    name: `${usersMocks[2].firstName} ${usersMocks[0].lastName}`,
    progress: false,
  },
  {
    id: usersMocks[3].id,
    name: `${usersMocks[3].firstName} ${usersMocks[0].lastName}`,
    progress: true,
  },
]
export const teamsQuestStatMocks: MembersCollapseData[] = [
  {
    id: teamsMocks[0].id,
    name: teamsMocks[0].name,
    progress: ((2 / 4) * 100).toString(),
    users: [
      usersQuestStatMocks[0],
      usersQuestStatMocks[1],
      usersQuestStatMocks[2],
      usersQuestStatMocks[3],
    ],
  },
  {
    id: teamsMocks[1].id,
    name: teamsMocks[1].name,
    progress: ((2 / 3) * 100).toString(),
    users: [usersQuestStatMocks[0], usersQuestStatMocks[2], usersQuestStatMocks[3]],
  },
  {
    id: teamsMocks[2].id,
    name: teamsMocks[2].name,
    progress: ((2 / 3) * 100).toString(),
    users: [usersQuestStatMocks[0], usersQuestStatMocks[2], usersQuestStatMocks[3]],
  },
]
export const QuestStatMocks: QuestCollapseData[] = [
  {
    idQuest: QuestsMocks[0].idQuest,
    isPass: true,
    idQuestTemplate: QuestsMocks[0].idQuestTemplate,
    name: QuestsMocks[0].name,
    progress: (
      (parseFloat(teamsQuestStatMocks[0].progress) +
        parseFloat(teamsQuestStatMocks[1].progress) +
        parseFloat(teamsQuestStatMocks[2].progress)) /
      3
    ).toString(),
    teams: [teamsQuestStatMocks[0], teamsQuestStatMocks[1], teamsQuestStatMocks[2]],
  },
  {
    idQuest: QuestsMocks[1].idQuest,
    isPass: true,
    idQuestTemplate: QuestsMocks[1].idQuestTemplate,
    name: QuestsMocks[1].name,
    progress: teamsQuestStatMocks[0].progress,
    teams: [teamsQuestStatMocks[0]],
  },
  {
    idQuest: QuestsMocks[2].idQuest,
    isPass: true,
    idQuestTemplate: QuestsMocks[2].idQuestTemplate,
    name: QuestsMocks[2].name,
    progress: teamsQuestStatMocks[0].progress,
    teams: [teamsQuestStatMocks[0]],
  },
  {
    idQuest: QuestsMocks[3].idQuest,
    isPass: true,
    idQuestTemplate: QuestsMocks[3].idQuestTemplate,
    name: QuestsMocks[3].name,
    progress: teamsQuestStatMocks[0].progress,
    teams: [teamsQuestStatMocks[0]],
  },
]

// Тесты
export const testMocks: Test[] = [
  {
    id: '1',
    testName: 'BelbinTest',
    name: 'Тест Белбина',
    description:
      'Состоит из 7 отдельных блоков по 8 вопросов или утверждений, с которыми вы можете согласиться или не согласиться. 	На каждый блок у Вас есть 10 очков. Присваивать очки можно не больше, чем 3м, утверждениям в блоке. При этом одному предложению можно присвоить минимум 2 очка. Если Вы согласны с каким-либо утверждением на все 100%, Вы можете отдать ему все 10 очков. Строго 10 нужно распоеделить.',
  },
  {
    id: '2',
    testName: 'TemperTest',
    name: 'Тест на тип темперамента',
    description:
      'Вам предлагается ответить на 57 вопросов. Вопросы направлены на выявление вашего обычного способа поведения. Постарайтесь представить типичные ситуации и дайте первый «естественный» ответ, который придет вам в голову. Отвечайте быстро и точно. Помните, что нет «хороших» или «плохих» ответов. Если вы согласны с утверждением, поставьте рядом с его номером знак + (да), если нет — знак — (нет).',
  },
  {
    id: '3',
    testName: 'MindTest',
    name: 'Тест на стиль мышления',
    description:
      'Каждый пункт данного опросника состоит из утверждения, за которым следует пять его возможных окончаний. Ваша задача – указать ту степень, в которой каждое окончание применимо к Вам. На бланке ответов напротив каждого окончания проставьте номера: 5, 4, 3, 2, или 1, указывающие на ту степень, в какой данное окончание применимо к Вам: от 5 (более всего подходит) до 1 (менее всего подходит). Каждый номер (балл) должен быть использован только один раз (!!!) в группе из пяти окончаний. ( Всего таких групп в опроснике 18). Даже если 2 окончания (или больше) в одной группе покажутся одинаково применимы к Вам, все-таки постарайтесь их упорядочить. Имейте ввиду, что для каждой группы каждый балл (5, 4, 3, 2 или 1) нельзя использовать более одного раза.',
  },
]
export const testQuestionsMocks: TestQuestion[] = [
  {
    id: '1',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question:
      'Я думаю, что я в состоянии быстро воспринимать и использовать новые возможности',
  },
  {
    id: '2',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Я легко кооперируюсь с людьми разных типов',
  },
  {
    id: '3',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Один из моих главных активов – продуцировать новые идеи',
  },
  {
    id: '4',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question:
      'Я способен вовлекать людей, которые, по моему мнению, могут сделать большой вклад в достижение групповых целей',
  },
  {
    id: '5',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question:
      'Мои личные способности позволяют эффективно доводить дело до самого конца',
  },
  {
    id: '6',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question:
      'Я не представляю себе даже временного снижения своей популярности, даже если это приведет к увеличению прибыли',
  },
  {
    id: '7',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Обычно я чувствую, что реалистично и что дееспособно',
  },
  {
    id: '8',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'КАКОЙ ВКЛАД Я МОГУ ВНЕСТИ В РАБОТУ КОМАНДЫ?',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question:
      'Я способен предложить весомые аргументы в пользу другой линии действий, не провоцируя при этом предубеждений и предвзятости',
  },
  {
    id: '9',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question:
      'Я чувствую себя неуютно на собраниях, даже если они четко структурированы и продуманно организованы',
  },
  {
    id: '10',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question:
      'Я склонен полагаться на людей, которые хорошо аргументируют свою точку зрения еще до того, как она была всесторонне обсуждена',
  },
  {
    id: '11',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question: 'Когда группа обсуждает новые идеи, я склонен слишком много говорить',
  },
  {
    id: '12',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question: 'Мои личные отношения мешают мне поддерживать коллег с энтузиазмом',
  },
  {
    id: '13',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question:
      'Когда надо сделать какое-либо дело, некоторые люди считают, что я действую агрессивно и авторитарно',
  },
  {
    id: '14',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question:
      'Я затрудняюсь брать на себя лидерскую роль, может потому, что слишком чувствителен к чувствам и настроениям группы',
  },
  {
    id: '15',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question:
      'У меня есть склонность настолько увлекаться собственными идеями, что я забываю о том, что происходит вокруг',
  },
  {
    id: '16',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'ЧТО ХАРАКТЕРИЗУЕТ МЕНЯ КАК ЧЛЕНА КОМАНДЫ',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question:
      'Мои коллеги считают, что я слишком забочусь о незначительных деталях и боюсь риска, что дело может быть испорчено',
  },
  {
    id: '17',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question:
      'Я могу хорошо влиять на других людей, при этом, не оказывая на них сильного давления',
  },
  {
    id: '18',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question:
      'Мое «шестое чувство» подсказывает  и  предохраняет меня от ошибок и инцидентов, которые иногда случаются из-за небрежности',
  },
  {
    id: '19',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question:
      'Во имя достижения главных целей, я готов ускорять события, не тратя время на обсуждения',
  },

  {
    id: '20',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question: 'От меня всегда можно ожидать чего-либо оригинального',
  },
  {
    id: '21',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question:
      'Я всегда готов поддержать хорошее предложение, которое принесет выгоду всем',
  },
  {
    id: '22',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question: 'Я постоянно отслеживаю  последние идеи и новейшие достижения',
  },
  {
    id: '23',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question:
      'Я думаю, что мои способности к  суждениям и оценкам могут внести большой вклад в принятие правильных решений',
  },
  {
    id: '24',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'КОГДА Я РАБОТАЮ С ДРУГИМИ НАД ПРОЕКТОМ',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question: 'На меня всегда можно положиться на завершающем этапе работы',
  },
  {
    id: '25',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question: 'Я искренне желаю узнать моих коллег получше',
  },
  {
    id: '26',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question:
      'Я не боюсь ни оспаривать точку зрения другого человека, ни остаться в меньшинстве',
  },
  {
    id: '27',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question: 'Обычно я могу доказать несостоятельность неудачного предложения',
  },
  {
    id: '28',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question:
      'Я думаю, что я способен хорошо выполнить любую функцию ради выполнения общего плана',
  },
  {
    id: '29',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question:
      'Часто я избегаю очевидных решений и прихожу вместо этого к неожиданным решениям проблемы',
  },
  {
    id: '30',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question: 'Я стремлюсь все что я делаю доводить до совершенства',
  },
  {
    id: '31',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question: 'Я готов использовать контакты вне группы',
  },
  {
    id: '32',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'МОЕ ОТНОШЕНИЕ И ИНТЕРЕС К ГРУППОВОЙ РАБОТЕ',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question:
      'Хотя я всегда открыт различным точкам зрения, я не испытываю трудностей при принятии решений',
  },
  {
    id: '33',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question:
      'Мне нравится анализировать ситуации и оценивать возможные направления деятельности',
  },
  {
    id: '34',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question: 'Мне интересно находить практические пути решения проблемы',
  },

  {
    id: '35',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question:
      'Мне приятно чувствовать, что я помогаю созданию хороших отношений на работе',
  },
  {
    id: '36',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question: 'Часто я имею сильное влияние на принимаемые решения',
  },
  {
    id: '37',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question:
      'Я имею открытые, приветливые отношения с людьми, которые могут предложить что-то новенькое',
  },
  {
    id: '38',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question: 'Я могу убеждать людей в необходимости определенной линии действий',
  },
  {
    id: '39',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question:
      'Я чувствую себя хорошо дома, когда я могу уделить максимум внимания заданию',
  },
  {
    id: '40',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'Я ЧУВСТВУЮ УДОВЛЕТВОРЕНИЕ ОТ РАБОТЫ, ПОТОМУ ЧТО',
    questionModuleNumber: 5,
    questionModule: 'Блок 5',
    question: 'Я люблю работать с чем-либо, что стимулирует мое воображение',
  },
  {
    id: '41',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question: 'Я откладываю дело на время и размышляю над проблемой',
  },
  {
    id: '42',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question:
      'Я готов сотрудничать с людьми, которые более позитивно и с большим  энтузиазмом относятся к проблеме',
  },
  {
    id: '43',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question:
      'Я пытаюсь сделать задание проще, подыскивая в группе людей, которые могут взять на себя решение части проблемы',
  },
  {
    id: '44',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question:
      'Мое врожденное ощущение времени позволяет мне выдерживать сроки выполнения задания',
  },
  {
    id: '45',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question: 'Я думаю, мне удастся сохранить ясность мысли и спокойствие',
  },
  {
    id: '46',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question: 'Даже под давлением внешних обстоятельств я не отступаю от цели',
  },
  {
    id: '47',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question:
      'Я готов взять лидерские обязанности на себя, если я чувствую, что группа не прогрессирует',
  },
  {
    id: '48',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'КОГДА  ЗАДАНИЕ  ТРУДНОЕ  И НЕЗНАКОМОЕ',
    questionModuleNumber: 6,
    questionModule: 'Блок 6',
    question:
      'Я бы начал дискуссию с целью стимулировать появление новых мыслей, способствующих решению проблемы',
  },
  {
    id: '49',
    testName: 'BelbinTest',
    questionNumber: 1,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question:
      'Я склонен выражать свое нетерпение по отношению к людям, которые стоят на пути развития прогресса (мешают)',
  },

  {
    id: '50',
    testName: 'BelbinTest',
    questionNumber: 2,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question:
      'Другие могут критиковать меня за то, что я слишком аналитичен и не подключаю интуицию',
  },
  {
    id: '51',
    testName: 'BelbinTest',
    questionNumber: 3,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question:
      'Мое желание убедиться в том, что работа выполняется с высоким качеством, может иногда привести к задержке',
  },
  {
    id: '52',
    testName: 'BelbinTest',
    questionNumber: 4,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question:
      'Мне быстро все надоедает, и я полагаюсь на то, что кто-то из группы стимулирует мой интерес',
  },
  {
    id: '53',
    testName: 'BelbinTest',
    questionNumber: 5,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question: 'Мне трудно приступить к решению задачи, не имея четкой цели',
  },
  {
    id: '54',
    testName: 'BelbinTest',
    questionNumber: 6,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question: 'Иногда мне трудно объяснить и описать проблему в комплексе',
  },
  {
    id: '55',
    testName: 'BelbinTest',
    questionNumber: 7,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question: 'Я знаю, что я требую от других того, что я сам не могу выполнить',
  },
  {
    id: '56',
    testName: 'BelbinTest',
    questionNumber: 8,
    questionName: 'ПРОБЛЕМЫ, ВОЗНИКАЮЩИЕ ПРИ РАБОТЕ В ГРУППАХ',
    questionModuleNumber: 7,
    questionModule: 'Блок 7',
    question:
      'Я затрудняюсь выражать собственное мнение, когда я нахожусь в очевидной оппозиции к большинству',
  },
  // Тест на темперамент
  {
    id: '60',
    testName: 'TemperTest',
    questionNumber: 1,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question:
      'Часто ли вы испытываете тягу к новым впечатлениям, к тому, чтобы отвлечься, испытывать сильные ощущения?',
  },
  {
    id: '61',
    testName: 'TemperTest',
    questionNumber: 2,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question:
      'Часто ли вы чувствуете, что нуждаетесь в друзьях, которые могут вас понять, ободрить или посочувствовать?',
  },
  {
    id: '62',
    testName: 'TemperTest',
    questionNumber: 3,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question: 'Считаете ли вы себя беззаботным человеком?  ',
  },
  {
    id: '63',
    testName: 'TemperTest',
    questionNumber: 4,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question: 'Очень ли трудно вам отказываться от своих намерений?  ',
  },
  {
    id: '64',
    testName: 'TemperTest',
    questionNumber: 5,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question:
      'Обдумываете ли вы свои дела не спеша и предпочитаете ли подождать, прежде чем действовать?  ',
  },
  {
    id: '65',
    testName: 'TemperTest',
    questionNumber: 6,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question: 'Всегда ли вы сдерживаете свои обещания, даже если это вам невыгодно?',
  },
  {
    id: '66',
    testName: 'TemperTest',
    questionNumber: 7,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question: 'Часто ли у вас бывают спады и подъемы настроения?',
  },
  {
    id: '67',
    testName: 'TemperTest',
    questionNumber: 8,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question:
      'Быстро ли вы обычно действуете и говорите, не тратите ли много времени на обдумывание?',
  },
  {
    id: '68',
    testName: 'TemperTest',
    questionNumber: 9,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question:
      'Возникало ли у вас когда-нибудь чувство, что вы несчастны, хотя никакой серьезной причины для этого не было?',
  },
  {
    id: '69',
    testName: 'TemperTest',
    questionNumber: 10,
    questionName: 'Тест на темперамент',
    questionModuleNumber: 0,
    questionModule: 'Тест',
    question: 'Верно ли, что на спор вы способны решиться на все?',
  },
  {
    id: '70',
    testName: 'MindTest',
    questionNumber: 1,
    questionName:
      'Когда между людьми имеет место конфликт на почве идей, я отдаю предпочтение той стороне, которая',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Устанавливает, определяет конфликт и пытается его выразить открыто',
  },
  {
    id: '71',
    testName: 'MindTest',
    questionNumber: 2,
    questionName:
      'Когда между людьми имеет место конфликт на почве идей, я отдаю предпочтение той стороне, которая',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Лучше всех выражает затрагиваемые ценности и идеалы',
  },
  {
    id: '72',
    testName: 'MindTest',
    questionNumber: 3,
    questionName:
      'Когда между людьми имеет место конфликт на почве идей, я отдаю предпочтение той стороне, которая',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Лучше всех отражает мои личные взгляды и опыт',
  },
  {
    id: '73',
    testName: 'MindTest',
    questionNumber: 4,
    questionName:
      'Когда между людьми имеет место конфликт на почве идей, я отдаю предпочтение той стороне, которая',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Подходит к ситуации наиболее логично и последовательно',
  },
  {
    id: '74',
    testName: 'MindTest',
    questionNumber: 5,
    questionName:
      'Когда между людьми имеет место конфликт на почве идей, я отдаю предпочтение той стороне, которая',
    questionModuleNumber: 1,
    questionModule: 'Блок 1',
    question: 'Излагает аргументы наиболее кратко и убедительно',
  },
  {
    id: '75',
    testName: 'MindTest',
    questionNumber: 1,
    questionName:
      'Когда я начинаю решать какие-либо проблемы совместно с другими людьми, самое важное для меня',
    questionModuleNumber: 2,
    questionModule: 'Блок 2',
    question: 'Понять цели и значение будущей работы',
  },
  {
    id: '76',
    testName: 'MindTest',
    questionNumber: 1,
    questionName: 'Вообще говоря, я усваиваю новые идеи лучше всего, когда могу',
    questionModuleNumber: 3,
    questionModule: 'Блок 3',
    question: 'Связать их с текущими или будущими своими занятиями',
  },
  {
    id: '77',
    testName: 'MindTest',
    questionNumber: 1,
    questionName: 'Для меня графики, схемы, чертежи в книгах или статьях обычно',
    questionModuleNumber: 4,
    questionModule: 'Блок 4',
    question: 'Полезнее текста, если они точны',
  },
]
export const testAnswerMocks: TestAnswer[] = [
  {
    id: '456',
    testName: 'BelbinTest',
    user: usersMocks[2],
    questionName: 'string',
    questionModuleNumber: 1,
    questionNumber: 4,
    answer: '4',
  },
]
export const testResultMocks: TestResult[] = [
  {
    id: '202',
    user: usersMocks[0],
    testName: 'BelbinTest',
    testResult: 'agagagagagga',
  },
  {
    id: '535',
    user: usersMocks[1],
    testName: 'BelbinTest',
    testResult: 'text',
  },
  {
    id: '65451',
    user: usersMocks[0],
    testName: 'TemperTest',
    testResult:
      'Холерик отличается повышенной возбудимостью, действия прерывисты. Ему свойственны резкость и стремительность движений, сила, импульсивность, яркая выраженность эмоциональных переживаний. Вследствие неуравновешенности, увлекшись делом, склонен действовать изо всех сил, истощаться больше, чем следует. Имея общественные интересы, темперамент проявляет в инициативности, энергичности, принципиальности. При отсутствии духовной жизни холерический темперамент часто проявляется в раздражительности, эффективности, несдержанности, вспыльчивости, неспособности к самоконтролю при эмоциональных обстоятельствах.',
  },
]
