name: CI/CD
on:
  push:
    branches:
      - production
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker buildx build \
            --build-arg VUE_APP_AUTH_API_URL=${{ secrets.VUE_APP_AUTH_API_URL }} \
            --build-arg VUE_APP_INVITATION_API_URL=${{ secrets.VUE_APP_INVITATION_API_URL }} \
            --build-arg VUE_APP_MANAGE_USERS_API_URL=${{ secrets.VUE_APP_MANAGE_USERS_API_URL }} \
            --build-arg VUE_APP_IDEAS_API_URL=${{ secrets.VUE_APP_IDEAS_API_URL }} \
            --build-arg VUE_APP_COMMENT_API_URL=${{ secrets.VUE_APP_COMMENT_API_URL }} \
            --build-arg VUE_APP_MANAGE_GROUPS_API_URL=${{ secrets.VUE_APP_MANAGE_GROUPS_API_URL }} \
            --build-arg VUE_APP_OAUTH_REDIRECT_URI=${{ secrets.VUE_APP_OAUTH_REDIRECT_URI }} \
            --build-arg VUE_APP_OAUTH_CLIENT_ID=${{ secrets.VUE_APP_OAUTH_CLIENT_ID }} \
            --build-arg VUE_APP_OAUTH_AUTH_HEADER=${{ secrets.VUE_APP_OAUTH_AUTH_HEADER }} \
            --build-arg VUE_APP_OAUTH_URL=${{ secrets.VUE_APP_OAUTH_URL }} \
            --build-arg VUE_APP_BACKEND_URL=${{ secrets.VUE_APP_BACKEND_URL }} \
            --build-arg VUE_APP_LOGOUT_URL=${{ secrets.VUE_APP_LOGOUT_URL }} \
            --tag ${{ secrets.DOCKER_LOGIN }}/hits:latest \
            --push \
            .
