name: CI/CD
on:
  push:
    branches:
      - production
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      VUE_APP_AUTH_API_URL: ${{ secrets.VUE_APP_AUTH_API_URL }}
      VUE_APP_INVITATION_API_URL: ${{ secrets.VUE_APP_INVITATION_API_URL }}
      VUE_APP_MANAGE_USERS_API_URL: ${{ secrets.VUE_APP_MANAGE_USERS_API_URL }}
      VUE_APP_IDEAS_API_URL: ${{ secrets.VUE_APP_IDEAS_API_URL }}
      VUE_APP_COMMENT_API_URL: ${{ secrets.VUE_APP_COMMENT_API_URL }}
      VUE_APP_MANAGE_GROUPS_API_URL: ${{ secrets.VUE_APP_MANAGE_GROUPS_API_URL }}
      VUE_APP_OAUTH_REDIRECT_URI: ${{ secrets.VUE_APP_OAUTH_REDIRECT_URI }}
      VUE_APP_OAUTH_CLIENT_ID: ${{ secrets.VUE_APP_OAUTH_CLIENT_ID }}
      VUE_APP_OAUTH_AUTH_HEADER: ${{ secrets.VUE_APP_OAUTH_AUTH_HEADER }}
      VUE_APP_OAUTH_URL: ${{ secrets.VUE_APP_OAUTH_URL }}
      VUE_APP_BACKEND_URL: ${{ secrets.VUE_APP_BACKEND_URL }}
      VUE_APP_LOGOUT_URL: ${{ secrets.VUE_APP_LOGOUT_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install dependecies
        run: npm ci
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build image
        with:
          VUE_APP_AUTH_API_URL: ${{ secrets.VUE_APP_AUTH_API_URL }}
          VUE_APP_INVITATION_API_URL: ${{ secrets.VUE_APP_INVITATION_API_URL }}
          VUE_APP_MANAGE_USERS_API_URL: ${{ secrets.VUE_APP_MANAGE_USERS_API_URL }}
          VUE_APP_IDEAS_API_URL: ${{ secrets.VUE_APP_IDEAS_API_URL }}
          VUE_APP_COMMENT_API_URL: ${{ secrets.VUE_APP_COMMENT_API_URL }}
          VUE_APP_MANAGE_GROUPS_API_URL: ${{ secrets.VUE_APP_MANAGE_GROUPS_API_URL }}
          VUE_APP_OAUTH_REDIRECT_URI: ${{ secrets.VUE_APP_OAUTH_REDIRECT_URI }}
          VUE_APP_OAUTH_CLIENT_ID: ${{ secrets.VUE_APP_OAUTH_CLIENT_ID }}
          VUE_APP_OAUTH_AUTH_HEADER: ${{ secrets.VUE_APP_OAUTH_AUTH_HEADER }}
          VUE_APP_OAUTH_URL: ${{ secrets.VUE_APP_OAUTH_URL }}
          VUE_APP_BACKEND_URL: ${{ secrets.VUE_APP_BACKEND_URL }}
          VUE_APP_LOGOUT_URL: ${{ secrets.VUE_APP_LOGOUT_URL }}
        run: |
          docker build .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/hits:latest
